#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioAnalyzer

#include "Basic.hpp"


namespace SDK::Params
{

// Function AudioAnalyzer.AudioAnalyzer.StartAnalyzing
// 0x0010 (0x0010 - 0x0000)
struct AudioAnalyzer_StartAnalyzing final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAudioBus*                              AudioBusToAnalyze;                                 // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AudioAnalyzer_StartAnalyzing;

// Function AudioAnalyzer.AudioAnalyzer.StopAnalyzing
// 0x0008 (0x0008 - 0x0000)
struct AudioAnalyzer_StopAnalyzing final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AudioAnalyzer_StopAnalyzing;

}

