#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bi_ToggleOverlapEvents

#include "Basic.hpp"


namespace SDK::Params
{

// Function Bi_ToggleOverlapEvents.Bi_ToggleOverlapEvents_C.EnableOverlaps
// 0x0008 (0x0008 - 0x0000)
struct Bi_ToggleOverlapEvents_C_EnableOverlaps final
{
public:
	double                                        Duration;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Bi_ToggleOverlapEvents_C_EnableOverlaps;

}

