#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Parent_Wyvern

#include "Basic.hpp"

#include "Char_Parent_Dragonkind_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Parent_Wyvern.Char_Parent_Wyvern_C
// 0x0000 (0x10F0 - 0x10F0)
class AChar_Parent_Wyvern_C : public AChar_Parent_Dragonkind_C
{
public:
	uint8                                         Pad_10E3[0x5];                                     // 0x10E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicsMovementGrabOffset_C*           PhysicsMovementGrabOffset;                         // 0x10E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnRep_ReplicatedFlightData();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Parent_Wyvern_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Parent_Wyvern_C")
	}
	static class AChar_Parent_Wyvern_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Parent_Wyvern_C>();
	}
};
DUMPER7_ASSERTS_AChar_Parent_Wyvern_C;

}

