#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Parent_Elemental_Tregon

#include "Basic.hpp"

#include "Char_Parent_Elemental_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Parent_Elemental_Tregon.Char_Parent_Elemental_Tregon_C
// 0x0000 (0x0CF0 - 0x0CF0)
class AChar_Parent_Elemental_Tregon_C final : public AChar_Parent_Elemental_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Parent_Elemental_Tregon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Parent_Elemental_Tregon_C")
	}
	static class AChar_Parent_Elemental_Tregon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Parent_Elemental_Tregon_C>();
	}
};
DUMPER7_ASSERTS_AChar_Parent_Elemental_Tregon_C;

}

