#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Parent_All

#include "Basic.hpp"

#include "Enum_Species_structs.hpp"
#include "Enum_GrowthStage_structs.hpp"
#include "Enum_StatusEffects_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Enum_CreatureLevels_structs.hpp"
#include "Struct_StatModifiers_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Enum_AnimMotionStates_structs.hpp"
#include "Enum_Temperature_structs.hpp"
#include "Enum_AppliedDamage_structs.hpp"
#include "Enum_GeneticGrades_structs.hpp"
#include "Enum_Diet_structs.hpp"
#include "Enum_StatMutations_structs.hpp"
#include "Enum_ServerType_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Parent_All.Char_Parent_All_C
// 0x0220 (0x0850 - 0x0630)
class AChar_Parent_All_C : public ACharacter
{
public:
	uint8                                         Pad_628[0x8];                                      // 0x0628(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0630(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFoliageInteraction_C*                  FoliageInteraction;                                // 0x0638(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      FX_DrippingWet;                                    // 0x0640(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    FX_BurningSound;                                   // 0x0648(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               FX_StatusBleeding;                                 // 0x0650(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               FX_StatusDecay;                                    // 0x0658(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               FX_StatusBurning;                                  // 0x0660(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAIPerceptionStimuliSourceComponent*    AIPerceptionStimuliSource;                         // 0x0668(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_PhysicsBlendWeight_B8E07A534AF6F6AE248960BE0F6696FA; // 0x0670(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_B8E07A534AF6F6AE248960BE0F6696FA; // 0x0674(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_675[0x3];                                      // 0x0675(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0678(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         WetnessDryOff_Wetness_A2AF8E1C492117E65FE406ACBAFEE50E; // 0x0680(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            WetnessDryOff__Direction_A2AF8E1C492117E65FE406ACBAFEE50E; // 0x0684(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_685[0x3];                                      // 0x0685(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     WetnessDryOff;                                     // 0x0688(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         BioGlowFade_Fade_1612190C4E0A5A08E183A69DF72C264B; // 0x0690(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            BioGlowFade__Direction_1612190C4E0A5A08E183A69DF72C264B; // 0x0694(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_695[0x3];                                      // 0x0695(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     BioGlowFade;                                       // 0x0698(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         SmoothGrow_Timeline_GrowthTick_DCE7EF9147680767222DDFBE8980E6B4; // 0x06A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            SmoothGrow_Timeline__Direction_DCE7EF9147680767222DDFBE8980E6B4; // 0x06A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A5[0x3];                                      // 0x06A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     SmoothGrow_Timeline;                               // 0x06A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EMovementMode                                 OldMovementMode;                                   // 0x06B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMovementMode                                 NewMovementMode;                                   // 0x06B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_AnimMotionStates                         MotionState;                                       // 0x06B2(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	Enum_AnimMotionStates                         LastMotionState;                                   // 0x06B3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsMoving;                                          // 0x06B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6B5[0x3];                                      // 0x06B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        WalkSpeedMultiplier;                               // 0x06B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPDA_DragonData_C*                      CreatureData;                                      // 0x06C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         SkinIndex;                                         // 0x06C8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Gender;                                            // 0x06C9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_6CA[0x6];                                      // 0x06CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Health;                                            // 0x06D0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	double                                        Armor;                                             // 0x06D8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         stamina;                                           // 0x06E0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Bile;                                              // 0x06E1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         hunger;                                            // 0x06E2(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Thirst;                                            // 0x06E3(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Torpor;                                            // 0x06E4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsDead;                                            // 0x06E5(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	Enum_GrowthStage                              GrowthStage;                                       // 0x06E6(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_6E7[0x1];                                      // 0x06E7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Growth;                                            // 0x06E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FTimerHandle                           TimerGrowthTick;                                   // 0x06F0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FStruct_StatModifiers                  StatModifiers;                                     // 0x06F8(0x0013)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsMiracleGrowActive;                               // 0x070B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAlpha;                                           // 0x070C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsSlowed;                                          // 0x070D(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRooted;                                          // 0x070E(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsStunned;                                         // 0x070F(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFrozen;                                          // 0x0710(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsPoisoned;                                        // 0x0711(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsBurning;                                         // 0x0712(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsBleeding;                                        // 0x0713(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsDecaying;                                        // 0x0714(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsUnconscious;                                     // 0x0715(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          IsWet;                                             // 0x0716(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Bioluminescence;                                   // 0x0717(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	double                                        LastBioluminescence;                               // 0x0718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRainWet;                                         // 0x0720(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSwimWet;                                         // 0x0721(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_Temperature                              Temperature;                                       // 0x0722(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsBeingDragged;                                    // 0x0723(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_724[0x4];                                      // 0x0724(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CorpseDespawnTimer;                                // 0x0728(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFast;                                            // 0x0730(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_731[0x3];                                      // 0x0731(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         FoodValue;                                         // 0x0734(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_Species                                  BiologicalSpecies;                                 // 0x0738(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_739[0x7];                                      // 0x0739(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UFMODAudioComponent*>            FMOD_HeardEvents;                                  // 0x0740(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FDateTime                              BeginPlayTimestamp;                                // 0x0750(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          CanJitterFix;                                      // 0x0758(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         HealthPercent;                                     // 0x0759(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_75A[0x6];                                      // 0x075A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AChar_Parent_Player_C*                  CorpseCarrier;                                     // 0x0760(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxFoodValue;                                      // 0x0768(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         FoodLeftPercent;                                   // 0x076C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_76D[0x3];                                      // 0x076D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CarcassClass;                                      // 0x0770(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDoingJitterFix;                                  // 0x0778(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_779[0x7];                                      // 0x0779(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDragonsGI_C*                           GameInstance;                                      // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CorpseBodyLocation;                                // 0x0788(0x0018)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          HasBeenDragged;                                    // 0x07A0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CorpseHasFinishedFalling;                          // 0x07A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A2[0x6];                                      // 0x07A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           MatEmissiveParamNames;                             // 0x07A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsBeingHitboxed;                                   // 0x07B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7B9[0x7];                                      // 0x07B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FVector& Origin)> CheckOverlaps;                      // 0x07C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnDeathListener;                                   // 0x07D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	double                                        GrowthRateScaleMultiplier;                         // 0x07E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SavedEmissionParam;                                // 0x07E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SavedEmissionAuxParam;                             // 0x07F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnSwimmingStart;                                   // 0x07F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnSwimmingStop;                                    // 0x0808(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	double                                        SavedWetnessFX;                                    // 0x0818(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    FMOD_MonVocalSFX;                                  // 0x0820(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        SavedIridescence;                                  // 0x0828(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsTempStunImmune;                                  // 0x0830(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	ETickingGroup                                 ActorTickGroup;                                    // 0x0831(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_832[0x6];                                      // 0x0832(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        SavedSkinEmissive;                                 // 0x0838(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SavedEmissiveBaseHue;                              // 0x0840(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SavedEmissiveStaticHue;                            // 0x0848(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddBioluminescence(class AChar_Parent_Player_C* PlayerInstigator);
	void AddPredatorPreyTag(Enum_Diet Diet);
	void AllBeginPlay();
	void AllEndPlay();
	void AllTick(double DeltaSeconds);
	void ApplyBioluminescence();
	void ApplyBleedStack(Enum_StatMutations StacksToApply);
	void ApplyBurnStack(Enum_StatMutations StacksToApply);
	void ApplyCreatureDamage(Enum_AppliedDamage AppliedDamage, class UClass* DamageTypeClass, bool UseRadialDamage, class AActor* SingleDamagedActor, const struct FVector& RadialDamageOrigin, double RadialDamageRadius, bool RadialIgnoreChannelPrevention, ECollisionChannel RadialDamagePreventionChannel, const TArray<class AActor*>& RadialIgnoreActors);
	void ApplyDecayStack(Enum_StatMutations StacksToApply);
	void ApplySkin();
	void ApplyStunStatus();
	void BioGlowFade__FinishedFunc();
	void BioGlowFade__UpdateFunc();
	void CalculateFlySpeed(double* TargetFlySpeed);
	void CalculateJumpVelocity(double* JumpVelocity);
	void CalculateSwimSpeed(double* TargetSwimSpeed);
	void CalculateWalkSpeed(double* TargetWalkSpeed);
	void CheckAnyPlayersInRange(double MeterRadius, bool* AnyHits);
	void CheckBodyAndSleep();
	void CheckFlushRagdoll();
	void CheckForNoneMovement();
	void CheckHitEnvironmentDestructable(class FName MeleeSocket, const struct FVector& HitBoxExtent, bool* Hit, class AActor** HitActor, struct FVector* HitOrigin);
	void CheckIfCanApplyBioluminescence(bool* BioPreventionActive);
	void CheckIfFast();
	void CheckIfMoving();
	void CheckIsStationary(bool* IsStationary);
	void CheckSafeLogTimer();
	void CheckSoundComponents();
	void CheckSoundMovementEvents(EMovementMode NewMovement, EMovementMode OldMovement);
	void ClearAllTimers();
	void DestroyCorpse();
	void DestroyRagdollComponent();
	void DetermineWetness();
	void DidJustBeginPlay(bool* JustRendered);
	void DigMound(class AAct_EggMound_C* EggMound);
	void DisableFlight();
	void DisplayTooltip();
	void DoJitterFix();
	void DryOff_RemoveWet();
	void EnableOverlaps(double Duration);
	void EnableRagdoll();
	void ExecuteUbergraph_Char_Parent_All(int32 EntryPoint);
	void FX_Bleeding();
	void FX_Burning();
	void FX_Decaying();
	void FX_StopAll();
	void FX_Stunned();
	void Get_Is_Ragdoll_Moving(bool* IsMoving_0);
	class UAnimInstance* Get_AnimBP();
	void Get_BleedTime(Enum_Species Species, double* BleedTimeSeconds);
	void Get_BloodPoolDecal(class UMaterialInstance** Decal, struct FVector* Size);
	void Get_BurnTime(Enum_Species Species, double* BurnTimeSeconds);
	void Get_DecayTime(Enum_Species Species, double* DecayTimeSeconds);
	void Get_GeneticOverallQuality(Enum_GeneticGrades* OverallQuality);
	void Get_MaxProjectileRange(double* RangeCM);
	void GetCreatureBloodDecalSize(struct FVector* DecalSize);
	void GetCreatureClass(Enum_CreatureLevels* ClassLevel);
	void GetCreatureDamage(Enum_AppliedDamage DamageSource, double* Damage);
	void GetCreatureHealth(double* MaxHealth, double* CurrentHealth, double* HealthPercent_0);
	void GetDamageModifiers(double InDamage, Enum_AppliedDamage DamageSource, double* OutDamage);
	void GetEnableHitboxData(class FName HitboxSocketName, struct FVector* HitboxSocketLoc, double* DetectionRadius);
	void GetFMOD_AgeParamFromParent(double* FMOD_AgeParam);
	void GetGenderSkinMaterial(class UMaterialInstance* MaleSkinMI, class UMaterialInstance* FemaleSkinMI, class UMaterialInstance** SkinMaterialInstance);
	void GetHitBoxExtent(class FName MeleeSocket, class FName MeleeEndSocket, bool IsFlying, struct FVector* HitBoxExtent);
	void GetIsActorMoving(bool* IsActorMoving);
	void GetIsFlying(bool* IsFlying);
	void GetIsMovementNone(bool* IsNone);
	void GetIsStatusImmune(Enum_StatusEffects StatusEffect, bool* IsImmune);
	void GetIsSwimming(bool* IsSwimming);
	void GetIsWalking(bool* IsWalking);
	void GetMotionState(Enum_AnimMotionStates* MotionState_0);
	void GetMovementMode(EMovementMode* MovementMode);
	void GetPhysicsDamping(double* LinearDamping, double* AngularDamping);
	void GetVenomPotency(uint8* Potency);
	void GetWalkSpeed(double* MaxWalkSpeed);
	void GrowthScaling();
	void GrowthTimer();
	void HandleCorpseReplication();
	void HatchlingGrowthBonus(double* GrowthBonus);
	void InjectVenom(uint8 VenomPotency);
	void Interp_ActorRotation(const struct FRotator& TargetRot, double TurnSpeed);
	void Interp_ActorRotationWithReturn(const struct FRotator& TargetRot, double InterpSpeed, double* Target_Y__Pitch_, double* Target_Z__Yaw_);
	void JitterBugFix(double TimelineFloat);
	void JuvenileGrowthBonus(double* GrowthBonus);
	void K2_OnMovementModeChanged(EMovementMode PrevMovementMode, EMovementMode NewMovementMode_0, uint8 PrevCustomMode, uint8 NewCustomMode);
	void MakeWet();
	void ManageGrowth();
	void MiracleGrow(bool IsDaily);
	void NoMoreMiracleGrow();
	void Normalize_HitDamageImpulse(const struct FVector& NormalImpulse, double* FallDamageNormalized);
	void OnActorInteraction(class AActor* Actor);
	void OnBleedUpdated();
	void OnBurnUpdated();
	void OnCharacterDamaged(double Damage, const class UDamageType* DamageType, class AController* DamageInstigator, class AActor* DamageCauser, bool IsRadial, const struct FVector& PointOfImpact, const struct FHitResult& HitInfo);
	void OnCharacterDeath_All_();
	void OnCharacterDeath_Local_();
	void OnCharacterDeath_Peer_();
	void OnCharacterDeath_Remote_();
	void OnCharacterDeath_Server_();
	void OnDecayUpdated();
	void OnEnvenomation(uint8 VenomTorpor);
	void OnGrowthChanged();
	void OnGrowthStageChangedRemote(Enum_GrowthStage NewGrowthStage);
	void OnGrowthStageChangedServer();
	void OnHungerUpdated();
	void OnInteraction(class AActor* InteractingActor);
	void OnMotionStateChanged();
	void OnMotionStateChangedServer();
	void OnPoisonedEvent();
	void OnRagdollBeingCarried();
	void OnRagdollReleased();
	void OnRep_Bioluminescence();
	void OnRep_CorpseBodyLocation();
	void OnRep_Growth();
	void OnRep_GrowthStage();
	void OnRep_Health();
	void OnRep_Hunger();
	void OnRep_IsBeingDragged();
	void OnRep_IsBleeding();
	void OnRep_IsBurning();
	void OnRep_IsDead();
	void OnRep_IsDecaying();
	void OnRep_IsPoisoned();
	void OnRep_IsStunned();
	void OnRep_IsTempStunImmune();
	void OnRep_IsUnconscious();
	void OnRep_IsWet();
	void OnRep_MotionState();
	void OnRep_Thirst();
	void OnStunUpdated();
	void OnSwimEnd();
	void OnSwimStart();
	void OnTempStunImmune();
	void OnThirstUpdated();
	void OnUnconsciousEvent();
	void OnWetUpdated();
	void ReceiveAnyDamage(float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveRadialDamage(float DamageReceived, const class UDamageType* DamageType, const struct FVector& Origin, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser);
	void ReceiveTick(float DeltaSeconds);
	void RefreshFX_BioGlow();
	void RefreshSkinParams();
	void ReinitPhysicsAsset();
	void RemoteBeginPlay();
	void RemoteEndPlay();
	void RemoteTick(double DeltaSeconds);
	void RemoveBioluminescence();
	void ReplicateMotionState(Enum_AnimMotionStates MotionState_0);
	void ReplicateMovementMode(EMovementMode NewMovementMode_0);
	void ReplicateRagdollLocation();
	void ResetDefaultRotation();
	void ResetRotation();
	void ScaleCharacterByGrowth();
	void ScaleComponentByGrowth(double GrowthScale);
	void ScaleHealthArmorWithGrowth();
	void ServerBeginPlay();
	void ServerEndPlay();
	void ServerSleepCorpse();
	void ServerTick(double DeltaSeconds);
	void Set_Death_Anim_BP();
	void Set_CarryBody();
	void Set_FoodValue();
	void Set_JumpVelocity(double JumpZVelocity);
	void Set_StatusBleeding(bool IsBleeding_0);
	void Set_StatusBurning(bool IsBurning_0);
	void Set_StatusDecaying(bool IsDecaying_0);
	void Set_StatusFrozen(bool IsFrozen_0);
	void Set_StatusPoisoned(bool IsPoisoned_0);
	void Set_StatusRooted(bool IsRooted_0);
	void Set_StatusSlowed(bool IsSlowed_0);
	void Set_StatusStunned(bool IsStunned_0);
	void Set_StatusUnconscious(bool IsUnconscious_0);
	void Set_StatusWet(bool IsWet_0);
	void SetActorTickGroup(ETickingGroup NewTickGroup);
	void SetAllMovementSpeeds();
	void SetCorpseDespawnTimer();
	void SetDefaultMeshValues();
	void SetFlySpeed(double MaxFlySpeed);
	void SetFoodValuePercent();
	void SetHealthPercent();
	void SetPhysicsDamping();
	void SetSwimSpeed(double MaxSwimSpeed);
	void SetWalkSpeed(double MaxWalkSpeed);
	void ShowEatenFX();
	void ShowWoundFX();
	void SmoothGrow_Timeline__FinishedFunc();
	void SmoothGrow_Timeline__UpdateFunc();
	void StopFlight();
	void StopJitterFix();
	void StoreMovementModes(EMovementMode OldMovementMode_0, EMovementMode NewMovementMode_0);
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();
	void ToggleCCD(bool InUseCCD);
	void TryDestroyCorpse();
	void TryDrop();
	void TryLaunchCharacter(const struct FVector& LaunchVelocity, bool XY_Override, bool Z_Override);
	void TryPickup(class AChar_Parent_Player_C* Player);
	void TrySpawnBloodHit();
	void TurnOffEmissives();
	void TurnOffWetPeer();
	void UpdateCorpseBodyLocation();
	void UserConstructionScript();
	void WetnessDryOff__FinishedFunc();
	void WetnessDryOff__UpdateFunc();

	void Get_Altitude(double* AltitudeMeters) const;
	void Get_CapsuleFloorLocation(struct FVector* Location) const;
	void GetCorpseDragHandle(class FName* CorpseDragHandle) const;
	void GetCreatureWeight(double* Weight) const;
	void GetDataAsset(class UPDA_DragonData_C** CreatureData_0) const;
	void GetRootBoneName(class FName* RootName) const;
	void IsTargetUnderwater(bool* IsUnderWater) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Parent_All_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Parent_All_C")
	}
	static class AChar_Parent_All_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Parent_All_C>();
	}
};
DUMPER7_ASSERTS_AChar_Parent_All_C;

}

