#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Dragon_BroodWatcher

#include "Basic.hpp"

#include "Char_Dragon_BroodWatcher_classes.hpp"
#include "Char_Dragon_BroodWatcher_parameters.hpp"


namespace SDK
{

// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.AllGlideJump
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::AllGlideJump()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "AllGlideJump");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ApplySkin
// (BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::ApplySkin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ApplySkin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.AssignNewEggGene
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStruct_PlayerEggInfo&     OldEgg                                                 (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   GeneIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CritResult                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStruct_PlayerEggInfo*           NewEgg                                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::AssignNewEggGene(const struct FStruct_PlayerEggInfo& OldEgg, uint8 GeneIndex, int32 CritResult, struct FStruct_PlayerEggInfo* NewEgg)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "AssignNewEggGene");

	Params::Char_Dragon_BroodWatcher_C_AssignNewEggGene Parms{};

	Parms.OldEgg = std::move(OldEgg);
	Parms.GeneIndex = GeneIndex;
	Parms.CritResult = CritResult;

	UObject::ProcessEvent(Func, &Parms);

	if (NewEgg != nullptr)
		*NewEgg = std::move(Parms.NewEgg);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.BndEvt__Char_Dragon_FlameStalker_WeaponBite_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AChar_Dragon_BroodWatcher_C::BndEvt__Char_Dragon_FlameStalker_WeaponBite_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "BndEvt__Char_Dragon_FlameStalker_WeaponBite_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::Char_Dragon_BroodWatcher_C_BndEvt__Char_Dragon_FlameStalker_WeaponBite_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.BndEvt__Char_Dragon_FlameStalker_WeaponSwipe_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AChar_Dragon_BroodWatcher_C::BndEvt__Char_Dragon_FlameStalker_WeaponSwipe_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "BndEvt__Char_Dragon_FlameStalker_WeaponSwipe_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::Char_Dragon_BroodWatcher_C_BndEvt__Char_Dragon_FlameStalker_WeaponSwipe_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.CalculateAllBroodingCrits
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   CritAttempts                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 CritChance                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 SuperCritChance                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 FailChance                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 CritFailChance                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::CalculateAllBroodingCrits(uint8 CritAttempts, double* CritChance, double* SuperCritChance, double* FailChance, double* CritFailChance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "CalculateAllBroodingCrits");

	Params::Char_Dragon_BroodWatcher_C_CalculateAllBroodingCrits Parms{};

	Parms.CritAttempts = CritAttempts;

	UObject::ProcessEvent(Func, &Parms);

	if (CritChance != nullptr)
		*CritChance = Parms.CritChance;

	if (SuperCritChance != nullptr)
		*SuperCritChance = Parms.SuperCritChance;

	if (FailChance != nullptr)
		*FailChance = Parms.FailChance;

	if (CritFailChance != nullptr)
		*CritFailChance = Parms.CritFailChance;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.CalculateBroodCritChance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// uint8                                   CritAttempts                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  CritChance                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::CalculateBroodCritChance(uint8 CritAttempts, uint8* CritChance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "CalculateBroodCritChance");

	Params::Char_Dragon_BroodWatcher_C_CalculateBroodCritChance Parms{};

	Parms.CritAttempts = CritAttempts;

	UObject::ProcessEvent(Func, &Parms);

	if (CritChance != nullptr)
		*CritChance = Parms.CritChance;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.CheckValidEmotePerSpecies
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// Enum_EmotesDragon                       Emote                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    HasEmotePack                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsValidEmote                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::CheckValidEmotePerSpecies(Enum_EmotesDragon Emote, bool HasEmotePack, bool* IsValidEmote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "CheckValidEmotePerSpecies");

	Params::Char_Dragon_BroodWatcher_C_CheckValidEmotePerSpecies Parms{};

	Parms.Emote = Emote;
	Parms.HasEmotePack = HasEmotePack;

	UObject::ProcessEvent(Func, &Parms);

	if (IsValidEmote != nullptr)
		*IsValidEmote = Parms.IsValidEmote;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ClientDispatchCraftTxtEvent
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   EventID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FStruct_StatModifiers&     EggStats                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::ClientDispatchCraftTxtEvent(uint8 EventID, const struct FStruct_StatModifiers& EggStats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ClientDispatchCraftTxtEvent");

	Params::Char_Dragon_BroodWatcher_C_ClientDispatchCraftTxtEvent Parms{};

	Parms.EventID = EventID;
	Parms.EggStats = std::move(EggStats);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ClientUpdateBroodEggs
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FStruct_PlayerEggInfo>&Eggs                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AChar_Dragon_BroodWatcher_C::ClientUpdateBroodEggs(const TArray<struct FStruct_PlayerEggInfo>& Eggs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ClientUpdateBroodEggs");

	Params::Char_Dragon_BroodWatcher_C_ClientUpdateBroodEggs Parms{};

	Parms.Eggs = std::move(Eggs);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ConvertGenes
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   CritResult                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   GeneByte                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_GeneticGrades                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

Enum_GeneticGrades AChar_Dragon_BroodWatcher_C::ConvertGenes(int32 CritResult, int32 GeneByte)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ConvertGenes");

	Params::Char_Dragon_BroodWatcher_C_ConvertGenes Parms{};

	Parms.CritResult = CritResult;
	Parms.GeneByte = GeneByte;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ExecuteUbergraph_Char_Dragon_BroodWatcher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::ExecuteUbergraph_Char_Dragon_BroodWatcher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ExecuteUbergraph_Char_Dragon_BroodWatcher");

	Params::Char_Dragon_BroodWatcher_C_ExecuteUbergraph_Char_Dragon_BroodWatcher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetBroodPouch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   HasEggs                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FStruct_PlayerEggInfo>*   BroodingPouchEggs_0                                    (Parm, OutParm)

void AChar_Dragon_BroodWatcher_C::GetBroodPouch(bool* HasEggs, TArray<struct FStruct_PlayerEggInfo>* BroodingPouchEggs_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetBroodPouch");

	Params::Char_Dragon_BroodWatcher_C_GetBroodPouch Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasEggs != nullptr)
		*HasEggs = Parms.HasEggs;

	if (BroodingPouchEggs_0 != nullptr)
		*BroodingPouchEggs_0 = std::move(Parms.BroodingPouchEggs_0);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetDamageModifiers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  InDamage                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_AppliedDamage                      DamageSource                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 OutDamage                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetDamageModifiers(double InDamage, Enum_AppliedDamage DamageSource, double* OutDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetDamageModifiers");

	Params::Char_Dragon_BroodWatcher_C_GetDamageModifiers Parms{};

	Parms.InDamage = InDamage;
	Parms.DamageSource = DamageSource;

	UObject::ProcessEvent(Func, &Parms);

	if (OutDamage != nullptr)
		*OutDamage = Parms.OutDamage;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetElementBileCost
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// uint8*                                  BileCost                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetElementBileCost(uint8* BileCost)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetElementBileCost");

	Params::Char_Dragon_BroodWatcher_C_GetElementBileCost Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BileCost != nullptr)
		*BileCost = Parms.BileCost;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetNewGeneValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   CritAttempts                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  CritValue                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  EventID                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetNewGeneValue(uint8 CritAttempts, int32* CritValue, uint8* EventID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetNewGeneValue");

	Params::Char_Dragon_BroodWatcher_C_GetNewGeneValue Parms{};

	Parms.CritAttempts = CritAttempts;

	UObject::ProcessEvent(Func, &Parms);

	if (CritValue != nullptr)
		*CritValue = Parms.CritValue;

	if (EventID != nullptr)
		*EventID = Parms.EventID;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetSpecialSkinIndexes
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// uint8*                                  Birthright                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  InfusedCrimson                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  Albino                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetSpecialSkinIndexes(uint8* Birthright, uint8* InfusedCrimson, uint8* Albino)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetSpecialSkinIndexes");

	Params::Char_Dragon_BroodWatcher_C_GetSpecialSkinIndexes Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Birthright != nullptr)
		*Birthright = Parms.Birthright;

	if (InfusedCrimson != nullptr)
		*InfusedCrimson = Parms.InfusedCrimson;

	if (Albino != nullptr)
		*Albino = Parms.Albino;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetStamDrainMultipliers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  DrainMultiplier                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetStamDrainMultipliers(int32* DrainMultiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetStamDrainMultipliers");

	Params::Char_Dragon_BroodWatcher_C_GetStamDrainMultipliers Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DrainMultiplier != nullptr)
		*DrainMultiplier = Parms.DrainMultiplier;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.GetStamRegenMultipliers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  RegenMultiplier                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::GetStamRegenMultipliers(int32* RegenMultiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "GetStamRegenMultipliers");

	Params::Char_Dragon_BroodWatcher_C_GetStamRegenMultipliers Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RegenMultiplier != nullptr)
		*RegenMultiplier = Parms.RegenMultiplier;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.HasAnyEggs
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   HasEggs                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::HasAnyEggs(bool* HasEggs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "HasAnyEggs");

	Params::Char_Dragon_BroodWatcher_C_HasAnyEggs Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasEggs != nullptr)
		*HasEggs = Parms.HasEggs;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.HasEgg1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   HasEgg1_0                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::HasEgg1(bool* HasEgg1_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "HasEgg1");

	Params::Char_Dragon_BroodWatcher_C_HasEgg1 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasEgg1_0 != nullptr)
		*HasEgg1_0 = Parms.HasEgg1_0;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.HasEgg2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   HasEgg2_0                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::HasEgg2(bool* HasEgg2_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "HasEgg2");

	Params::Char_Dragon_BroodWatcher_C_HasEgg2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasEgg2_0 != nullptr)
		*HasEgg2_0 = Parms.HasEgg2_0;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.HornAll
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::HornAll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "HornAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.HornServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::HornServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "HornServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.IncreaseHunger
// (Public, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::IncreaseHunger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "IncreaseHunger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.InpActEvt_Attack2_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::InpActEvt_Attack2_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "InpActEvt_Attack2_K2Node_InputActionEvent_1");

	Params::Char_Dragon_BroodWatcher_C_InpActEvt_Attack2_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.InpActEvt_Attack_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::InpActEvt_Attack_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "InpActEvt_Attack_K2Node_InputActionEvent_0");

	Params::Char_Dragon_BroodWatcher_C_InpActEvt_Attack_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.LocalTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::LocalTick(double DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "LocalTick");

	Params::Char_Dragon_BroodWatcher_C_LocalTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.MulticastSpikeThrow
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   TargetLoc                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   LocalCameraLoc                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::MulticastSpikeThrow(const struct FVector& TargetLoc, const struct FVector& LocalCameraLoc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "MulticastSpikeThrow");

	Params::Char_Dragon_BroodWatcher_C_MulticastSpikeThrow Parms{};

	Parms.TargetLoc = std::move(TargetLoc);
	Parms.LocalCameraLoc = std::move(LocalCameraLoc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.NotifyServerSpikeThrow
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   TargetLoc                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   LocalCameraLoc                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::NotifyServerSpikeThrow(const struct FVector& TargetLoc, const struct FVector& LocalCameraLoc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "NotifyServerSpikeThrow");

	Params::Char_Dragon_BroodWatcher_C_NotifyServerSpikeThrow Parms{};

	Parms.TargetLoc = std::move(TargetLoc);
	Parms.LocalCameraLoc = std::move(LocalCameraLoc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_0D0C28034CC69F3F8D003E9DB005B091
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_0D0C28034CC69F3F8D003E9DB005B091");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_0D0C28034CC69F3F8D003E9DB005B091 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_3872EC4A43B4343191551883D031C95F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_3872EC4A43B4343191551883D031C95F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_3872EC4A43B4343191551883D031C95F");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_3872EC4A43B4343191551883D031C95F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_45BA59314E10CB3E47E6A19C6BBA884E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_45BA59314E10CB3E47E6A19C6BBA884E");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_45BA59314E10CB3E47E6A19C6BBA884E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_977E1ACF4EB9DB9761904AA70C9B60CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_977E1ACF4EB9DB9761904AA70C9B60CB");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_977E1ACF4EB9DB9761904AA70C9B60CB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_D102FEBE4FD5CAD9A5E97E884CE486C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_D102FEBE4FD5CAD9A5E97E884CE486C5");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_D102FEBE4FD5CAD9A5E97E884CE486C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnBlendOut_DB2FD6C5454834C97C8757830A80F316
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnBlendOut_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnBlendOut_DB2FD6C5454834C97C8757830A80F316");

	Params::Char_Dragon_BroodWatcher_C_OnBlendOut_DB2FD6C5454834C97C8757830A80F316 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_0D0C28034CC69F3F8D003E9DB005B091
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_0D0C28034CC69F3F8D003E9DB005B091");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_0D0C28034CC69F3F8D003E9DB005B091 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_3872EC4A43B4343191551883D031C95F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_3872EC4A43B4343191551883D031C95F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_3872EC4A43B4343191551883D031C95F");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_3872EC4A43B4343191551883D031C95F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_45BA59314E10CB3E47E6A19C6BBA884E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_45BA59314E10CB3E47E6A19C6BBA884E");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_45BA59314E10CB3E47E6A19C6BBA884E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_977E1ACF4EB9DB9761904AA70C9B60CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_977E1ACF4EB9DB9761904AA70C9B60CB");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_977E1ACF4EB9DB9761904AA70C9B60CB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_D102FEBE4FD5CAD9A5E97E884CE486C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_D102FEBE4FD5CAD9A5E97E884CE486C5");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_D102FEBE4FD5CAD9A5E97E884CE486C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnCompleted_DB2FD6C5454834C97C8757830A80F316
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnCompleted_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnCompleted_DB2FD6C5454834C97C8757830A80F316");

	Params::Char_Dragon_BroodWatcher_C_OnCompleted_DB2FD6C5454834C97C8757830A80F316 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_0D0C28034CC69F3F8D003E9DB005B091
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_0D0C28034CC69F3F8D003E9DB005B091");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_0D0C28034CC69F3F8D003E9DB005B091 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_3872EC4A43B4343191551883D031C95F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_3872EC4A43B4343191551883D031C95F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_3872EC4A43B4343191551883D031C95F");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_3872EC4A43B4343191551883D031C95F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_45BA59314E10CB3E47E6A19C6BBA884E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_45BA59314E10CB3E47E6A19C6BBA884E");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_45BA59314E10CB3E47E6A19C6BBA884E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_977E1ACF4EB9DB9761904AA70C9B60CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_977E1ACF4EB9DB9761904AA70C9B60CB");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_977E1ACF4EB9DB9761904AA70C9B60CB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_D102FEBE4FD5CAD9A5E97E884CE486C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_D102FEBE4FD5CAD9A5E97E884CE486C5");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_D102FEBE4FD5CAD9A5E97E884CE486C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnInterrupted_DB2FD6C5454834C97C8757830A80F316
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnInterrupted_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnInterrupted_DB2FD6C5454834C97C8757830A80F316");

	Params::Char_Dragon_BroodWatcher_C_OnInterrupted_DB2FD6C5454834C97C8757830A80F316 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnJump
// (BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::OnJump()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnJump");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnJumped
// (Event, Public, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::OnJumped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnJumped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnLanded
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AChar_Dragon_BroodWatcher_C::OnLanded(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnLanded");

	Params::Char_Dragon_BroodWatcher_C_OnLanded Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnMulticastedEmote
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_EmotesDragon                       Emote                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnMulticastedEmote(Enum_EmotesDragon Emote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnMulticastedEmote");

	Params::Char_Dragon_BroodWatcher_C_OnMulticastedEmote Parms{};

	Parms.Emote = Emote;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_0D0C28034CC69F3F8D003E9DB005B091
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_0D0C28034CC69F3F8D003E9DB005B091");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_0D0C28034CC69F3F8D003E9DB005B091 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_3872EC4A43B4343191551883D031C95F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_3872EC4A43B4343191551883D031C95F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_3872EC4A43B4343191551883D031C95F");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_3872EC4A43B4343191551883D031C95F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_45BA59314E10CB3E47E6A19C6BBA884E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_45BA59314E10CB3E47E6A19C6BBA884E");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_45BA59314E10CB3E47E6A19C6BBA884E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_977E1ACF4EB9DB9761904AA70C9B60CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_977E1ACF4EB9DB9761904AA70C9B60CB");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_977E1ACF4EB9DB9761904AA70C9B60CB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_D102FEBE4FD5CAD9A5E97E884CE486C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_D102FEBE4FD5CAD9A5E97E884CE486C5");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_D102FEBE4FD5CAD9A5E97E884CE486C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyBegin_DB2FD6C5454834C97C8757830A80F316
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyBegin_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyBegin_DB2FD6C5454834C97C8757830A80F316");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyBegin_DB2FD6C5454834C97C8757830A80F316 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_0D0C28034CC69F3F8D003E9DB005B091
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_0D0C28034CC69F3F8D003E9DB005B091");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_0D0C28034CC69F3F8D003E9DB005B091 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_3872EC4A43B4343191551883D031C95F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_3872EC4A43B4343191551883D031C95F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_3872EC4A43B4343191551883D031C95F");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_3872EC4A43B4343191551883D031C95F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_45BA59314E10CB3E47E6A19C6BBA884E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_45BA59314E10CB3E47E6A19C6BBA884E");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_45BA59314E10CB3E47E6A19C6BBA884E Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_977E1ACF4EB9DB9761904AA70C9B60CB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_977E1ACF4EB9DB9761904AA70C9B60CB");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_977E1ACF4EB9DB9761904AA70C9B60CB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_D102FEBE4FD5CAD9A5E97E884CE486C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_D102FEBE4FD5CAD9A5E97E884CE486C5");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_D102FEBE4FD5CAD9A5E97E884CE486C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.OnNotifyEnd_DB2FD6C5454834C97C8757830A80F316
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::OnNotifyEnd_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "OnNotifyEnd_DB2FD6C5454834C97C8757830A80F316");

	Params::Char_Dragon_BroodWatcher_C_OnNotifyEnd_DB2FD6C5454834C97C8757830A80F316 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ReceiveAsyncPhysicsTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   SimSeconds                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::ReceiveAsyncPhysicsTick(float DeltaSeconds, float SimSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ReceiveAsyncPhysicsTick");

	Params::Char_Dragon_BroodWatcher_C_ReceiveAsyncPhysicsTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;
	Parms.SimSeconds = SimSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ReceiveHit
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              MyComp                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Other                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    bSelfMoved                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitNormal                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AChar_Dragon_BroodWatcher_C::ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ReceiveHit");

	Params::Char_Dragon_BroodWatcher_C_ReceiveHit Parms{};

	Parms.MyComp = MyComp;
	Parms.Other = Other;
	Parms.OtherComp = OtherComp;
	Parms.bSelfMoved = bSelfMoved;
	Parms.HitLocation = std::move(HitLocation);
	Parms.HitNormal = std::move(HitNormal);
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ServerAttemptEnhanceStat
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   EggIndex                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   GeneIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::ServerAttemptEnhanceStat(uint8 EggIndex, uint8 GeneIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ServerAttemptEnhanceStat");

	Params::Char_Dragon_BroodWatcher_C_ServerAttemptEnhanceStat Parms{};

	Parms.EggIndex = EggIndex;
	Parms.GeneIndex = GeneIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ServerGlideJump
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::ServerGlideJump()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ServerGlideJump");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.ServerRequestPouchInterface
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::ServerRequestPouchInterface()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "ServerRequestPouchInterface");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.SpecialUsesStatusBar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::SpecialUsesStatusBar(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "SpecialUsesStatusBar");

	Params::Char_Dragon_BroodWatcher_C_SpecialUsesStatusBar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.SwipeAll
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_YawDirection                       Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::SwipeAll(Enum_YawDirection Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "SwipeAll");

	Params::Char_Dragon_BroodWatcher_C_SwipeAll Parms{};

	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.SwipeServer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_YawDirection                       Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AChar_Dragon_BroodWatcher_C::SwipeServer(Enum_YawDirection Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "SwipeServer");

	Params::Char_Dragon_BroodWatcher_C_SwipeServer Parms{};

	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AChar_Dragon_BroodWatcher_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Char_Dragon_BroodWatcher_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

