#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Parent_Dragonkind

#include "Basic.hpp"

#include "Enum_EmotesDragon_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Enum_SkinOverlays_structs.hpp"
#include "Enum_StatMutations_structs.hpp"
#include "Enum_Elements_structs.hpp"
#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"
#include "Enum_MapRegion_structs.hpp"
#include "Struct_Lineage_structs.hpp"
#include "Enum_Cosmetic_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "Struct_StatRecessives_structs.hpp"
#include "Char_Parent_Player_classes.hpp"
#include "Enum_GrowthStage_structs.hpp"
#include "Enum_AnimMotionStates_structs.hpp"
#include "Enum_Species_structs.hpp"
#include "Enum_CrystalColor_structs.hpp"
#include "Enum_ServerType_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Parent_Dragonkind.Char_Parent_Dragonkind_C
// 0x0420 (0x1100 - 0x0CE0)
#pragma pack(push, 0x1)
class alignas(0x10) AChar_Parent_Dragonkind_C : public AChar_Parent_Player_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Char_Parent_Dragonkind_C;           // 0x0CE0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UQuestTracker_C*                        QuestTracker;                                      // 0x0CE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPlayerInventory_C*                     PlayerInventory;                                   // 0x0CF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    FlyByLoop;                                         // 0x0CF8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    DiveBombLoop;                                      // 0x0D00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CosmeticEffect;                                    // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    AudioFlightLoop;                                   // 0x0D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFMODAudioComponent*                    AudioSwimLoop;                                     // 0x0D18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   SireSID;                                           // 0x0D20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FName                                   DamSID;                                            // 0x0D28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsAnimationPlaying;                                // 0x0D30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInputRestPressed;                                // 0x0D31(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         WaterBuoyancy;                                     // 0x0D32(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D33[0x5];                                      // 0x0D33(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                NestWaypoint;                                      // 0x0D38(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasNest;                                           // 0x0D50(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D51[0x7];                                      // 0x0D51(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                TempNestWP;                                        // 0x0D58(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanDropNest;                                       // 0x0D70(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D71[0x3];                                      // 0x0D71(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ServerNestID;                                      // 0x0D74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           HealthRegenTimer;                                  // 0x0D78(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHealthRegenerating;                              // 0x0D80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D81[0x7];                                      // 0x0D81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AChar_Parent_Dragonkind_C*              Mate;                                              // 0x0D88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ASpawn_DragonNest_C*                    FemaleNest;                                        // 0x0D90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class ASpawn_DragonNest_C*>            MaleNests;                                         // 0x0D98(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          IsBeingCourted;                                    // 0x0DA8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA9[0x7];                                      // 0x0DA9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 DragonNestClass;                                   // 0x0DB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsBeingCarried;                                    // 0x0DB8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DB9[0x7];                                      // 0x0DB9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AChar_Parent_Dragonkind_C*              CarrierActor;                                      // 0x0DC0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AChar_Parent_Dragonkind_C*              CarriedActor;                                      // 0x0DC8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsStruggling;                                      // 0x0DD0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DD1[0x7];                                      // 0x0DD1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              DispatchStruggleMontage;                           // 0x0DD8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	struct FTimerHandle                           ArmorRegenTimer;                                   // 0x0DE8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsArmorRegenerating;                               // 0x0DF0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasBileExhaustion;                                 // 0x0DF1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasStaminaExhaustion;                              // 0x0DF2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasTorpor;                                         // 0x0DF3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DF4[0x4];                                      // 0x0DF4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           PoisonTimer;                                       // 0x0DF8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        CurePoisonTimeCounter;                             // 0x0E00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          BileFull;                                          // 0x0E08(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E09[0x7];                                      // 0x0E09(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CureBleedTimeCounter;                              // 0x0E10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CureDecayTimeCounter;                              // 0x0E18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CureBurnTimeCounter;                               // 0x0E20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_StatMutations                            BleedStacks;                                       // 0x0E28(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	Enum_StatMutations                            DecayStacks;                                       // 0x0E29(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E2A[0x6];                                      // 0x0E2A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              DispatchYelp;                                      // 0x0E30(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	bool                                          IsAttackOnCooldown;                                // 0x0E40(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsBiting;                                          // 0x0E41(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E42[0x6];                                      // 0x0E42(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 ProjectileTarget;                                  // 0x0E48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FString                                 TargetData;                                        // 0x0E50(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	struct FVector                                LastBleedLoc;                                      // 0x0E60(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDateTime                              LastBleedTime;                                     // 0x0E78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          MuteFlyBy;                                         // 0x0E80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E81[0x7];                                      // 0x0E81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   Key_Rest;                                          // 0x0E88(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FKey                                   Key_SwimBladderUp;                                 // 0x0EA0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FKey                                   Key_SwimBladderDown;                               // 0x0EB8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FKey                                   Key_AirBoost;                                      // 0x0ED0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FKey                                   Key_AirBrake;                                      // 0x0EE8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          IsDeathFoodValueOne;                               // 0x0F00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_Cosmetic                                 CosmeticFX;                                        // 0x0F01(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FStruct_StatRecessives                 RecessiveGenes;                                    // 0x0F02(0x0012)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	Enum_StatMutations                            BurnStacks;                                        // 0x0F14(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F15[0x3];                                      // 0x0F15(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              LastGrowthTime;                                    // 0x0F18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FTimerHandle                           DailyGrowthTimer;                                  // 0x0F20(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FKey                                   KeyJump;                                           // 0x0F28(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool ShouldFly)> ToggleFlight;                                     // 0x0F40(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	TMulticastInlineDelegate<void()>              BreakMomentum;                                     // 0x0F50(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	bool                                          IsBoostFlying;                                     // 0x0F60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F61[0x7];                                      // 0x0F61(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CarriedFromLoc;                                    // 0x0F68(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldPauseStaminaRegen;                           // 0x0F80(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F81[0x7];                                      // 0x0F81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        HoverYaw;                                          // 0x0F88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GlideRegenCounter;                                 // 0x0F90(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F91[0x3];                                      // 0x0F91(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SecondWindStamina;                                 // 0x0F94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(Enum_EmotesDragon Emote)> OnEmoteFired;                            // 0x0F98(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, AdvancedDisplay, BlueprintCallable)
	Enum_MapRegion                                NestLocationBiome;                                 // 0x0FA8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         SecondWindRep;                                     // 0x0FA9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FAA[0x2];                                      // 0x0FAA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_Lineage                        Lineage;                                           // 0x0FAC(0x0114)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         PlayerStaminaExhaustion;                           // 0x10C0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	Enum_SkinOverlays                             SkinOverride;                                      // 0x10C1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         RecessiveSkin;                                     // 0x10C2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         RecessiveEyes;                                     // 0x10C3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         EyesIndex;                                         // 0x10C4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         ShimmerValue;                                      // 0x10C5(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_10C6[0x2];                                     // 0x10C6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        SpecialBarCurrentValue;                            // 0x10C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SpecialBarMaxValue;                                // 0x10D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_StatMutations                            StunLevels;                                        // 0x10D8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          WasRecentlyStunned;                                // 0x10D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10DA[0x6];                                     // 0x10DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FVector& NormalImpulse)> WantsFlightHit;              // 0x10E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          RecentlyRegurgitated;                              // 0x10F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         StaticSkinEmissiveValue;                           // 0x10F1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         SkinPattern;                                       // 0x10F2(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         StaticEmissiveHueValue;                            // 0x10F3(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         BaseEmissiveHueValue;                              // 0x10F4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void All_Scent(bool Stop);
	void ApplyBleed(Enum_StatMutations Stacks);
	void ApplyBleedStack(Enum_StatMutations StacksToApply);
	void ApplyBurn(Enum_StatMutations Stacks);
	void ApplyBurnStack(Enum_StatMutations StacksToApply);
	void ApplyDecay(Enum_StatMutations Stacks);
	void ApplyDecayStack(Enum_StatMutations StacksToApply);
	void ApplySkinPattern();
	void ApplyStun();
	void ApplyStunStatus();
	void ApplyTorpor(bool UsePercentage, double AddPercent, int32 AddValue);
	void BileRegenLoop();
	void BlastSoundwave(Enum_CrystalColor Attunement);
	void BndEvt__Char_Parent_Dragonkind_TemperatureWeatherStatus_K2Node_ComponentBoundEvent_0_Exposed_to_Rain__DelegateSignature();
	void BndEvt__Char_Parent_Dragonkind_TemperatureWeatherStatus_K2Node_ComponentBoundEvent_0_Not_Exposed_to_Rain__DelegateSignature();
	void BreakFree();
	void Calc_FlightStaminaDrain(int32 PlayerMaxStam, int32* StaminaCost);
	void CalculateAbilityBileDrain(int32* CostBile);
	void CalculateAbilityStamDrain(int32* CostStamina);
	void CalculateArmorRegen(bool* IsArmorFull);
	void CalculateBileRegen(bool* IsBileFull, bool* IsBileDepleted);
	void CalculateHealthRegen(bool* IsHealthFull);
	void CalculateStamina(bool* IsStaminaDepleted, int32* HalfStamina);
	void ChangeElementColorOverride(bool Reset);
	void Cheat0();
	void CheckDehydration();
	void CheckForBeingNoisey();
	void CheckForIconsOnPossess();
	void CheckHasTorpor(bool* HasTorpor_0);
	void CheckHunger();
	void CheckLoginStatusFX();
	void CheckMaleCanHaveMoreNests(bool* CanHaveMoreNests);
	void CheckOnPoisonedEvent();
	void CheckPlayHatchieMusic();
	void CheckShouldCureTorpor();
	void CheckShouldRegenArmor(bool* ShouldRegen);
	void CheckShouldRegenBile(bool* ShouldRegenBile);
	void CheckShouldRegenHealth(bool* ShouldRegen);
	void CheckSoundComponents();
	void CheckSoundMovementEvents(EMovementMode NewMovement, EMovementMode OldMovement);
	void CheckStaminaDrainRegen();
	void CheckStarvation();
	void CheckThirst();
	void CheckTorporMaxed(bool* ShouldTakeDamage);
	void CheckUniqueEmoteConditions(bool* CanEmote);
	void CheckValidEmotePerSpecies(Enum_EmotesDragon Emote, bool HasEmotePack, bool* IsValidEmote);
	void ClearAllTimers();
	void Client_SetMate(class AChar_Parent_Dragonkind_C* Mate_0);
	void Client_SetNest(class ASpawn_DragonNest_C* Nest);
	void ClientNestingNotify(uint8 MessageID);
	void Construct_Buoyancy();
	void CostBile(bool UsePercent, double CostPercent, uint8 CostValue);
	void CostStamina(bool UsePercent, double CostPercent, uint8 CostValue);
	void CourtshipCooldownTimer();
	void CritHit();
	void CurePoison();
	void DailyGrowthChecks(bool JustBecameAdult);
	void DamageSelf(double BaseDamage, class UClass* DamageTypeClass);
	void DeliverSireDame(class FName Sire, class FName Dame, const struct FStruct_Lineage& Lineage_0);
	void DestroyNest();
	void DisableFlight();
	void DisableSpecial();
	void DoDragonkindScreenFX();
	void DoForAllEmotes();
	void DropActor();
	void EmoteCourtship();
	void EmoteDistress();
	void EmoteFear();
	void EmoteFriendly();
	void EmoteLaugh();
	void EmoteLove();
	void EmoteNope();
	void EmoteRage();
	void EmoteRoar();
	void EmoteSad();
	void EmoteTaunt();
	void EmoteThreaten();
	void EnableCVC_PVP();
	void ExecuteUbergraph_Char_Parent_Dragonkind(int32 EntryPoint);
	void FadeEyesOnDeath();
	void FemalBuildNest();
	void ForceReleaseSprint();
	void Get_Apply_Skin_ID(class FName* SkinRow);
	void Get_IsHovering(bool* IsHovering);
	void GetAimTargetLocation(double DistanceM, struct FVector* Aimpoint);
	void GetBileExhaustionRecoveryTime(double* Seconds);
	void GetBilePercent(double* BilePercent);
	void GetBloodDecal(class UMaterialInstance** DecalMat, struct FVector* Size);
	void GetBoneTargetLocation(double DistanceM, bool* UseBoneTarget, class ACharacter** HitCharacter, class FName* HitBone);
	void GetBreathLookAtPoint(double RangeCM, bool TargetCreatureOnly, bool RotateBreathToHead, class FName HeadJointName, class FName ElementSocketName, struct FVector* LookAtPoint);
	void GetCarryOffset(double* RotOffset);
	void GetElementBileCost(uint8* BileCost);
	void GetHasEnoughBile(uint8 BileCost, bool* HasEnoughBile);
	void GetHasEnoughStamForJump(bool* CanJumpWithStam);
	void GetHasEnoughStamina(uint8 StamCost, bool* HasEnoughStamina);
	void GetProjectileTransform(class FName SocketStart, const struct FVector& Target, struct FTransform* SpawnTransform);
	void GetSpecialSkinIndexes(uint8* Birthright, uint8* InfusedCrimson, uint8* Albino);
	void GetStamDrainMultipliers(int32* DrainMultiplier);
	void GetStamRegenMultipliers(int32* RegenMultiplier);
	void HatchlingGrowthBonus(double* GrowthBonus);
	void HealBleed();
	void HealBleedInstant();
	void HealBurn();
	void HealDecay();
	void IncreaseHunger();
	void IncreaseThirst();
	void InitiateCourtship();
	void InpActEvt_BuildNest_K2Node_InputActionEvent_2(const struct FKey& Key);
	void InpActEvt_EmoteCare_K2Node_InputActionEvent_18(const struct FKey& Key);
	void InpActEvt_EmoteChallenge_K2Node_InputActionEvent_16(const struct FKey& Key);
	void InpActEvt_EmoteCourt_K2Node_InputActionEvent_19(const struct FKey& Key);
	void InpActEvt_EmoteDistress_K2Node_InputActionEvent_14(const struct FKey& Key);
	void InpActEvt_EmoteFear_K2Node_InputActionEvent_21(const struct FKey& Key);
	void InpActEvt_EmoteFriendly_K2Node_InputActionEvent_20(const struct FKey& Key);
	void InpActEvt_EmoteLaugh_K2Node_InputActionEvent_13(const struct FKey& Key);
	void InpActEvt_EmoteMourn_K2Node_InputActionEvent_17(const struct FKey& Key);
	void InpActEvt_EmoteNo_K2Node_InputActionEvent_12(const struct FKey& Key);
	void InpActEvt_EmoteRage_K2Node_InputActionEvent_15(const struct FKey& Key);
	void InpActEvt_EmoteRoar_K2Node_InputActionEvent_23(const struct FKey& Key);
	void InpActEvt_EmoteThreaten_K2Node_InputActionEvent_22(const struct FKey& Key);
	void InpActEvt_Jump_K2Node_InputActionEvent_5(const struct FKey& Key);
	void InpActEvt_Jump_K2Node_InputActionEvent_6(const struct FKey& Key);
	void InpActEvt_Rest_K2Node_InputActionEvent_10(const struct FKey& Key);
	void InpActEvt_Rest_K2Node_InputActionEvent_11(const struct FKey& Key);
	void InpActEvt_Scent_K2Node_InputActionEvent_0(const struct FKey& Key);
	void InpActEvt_Scent_K2Node_InputActionEvent_1(const struct FKey& Key);
	void InpActEvt_Sprint_K2Node_InputActionEvent_7(const struct FKey& Key);
	void InpActEvt_Sprint_K2Node_InputActionEvent_8(const struct FKey& Key);
	void InpActEvt_Stalk_K2Node_InputActionEvent_9(const struct FKey& Key);
	void InpActEvt_SwimBladderDown_K2Node_InputActionEvent_3(const struct FKey& Key);
	void InpActEvt_SwimBladderUp_K2Node_InputActionEvent_4(const struct FKey& Key);
	void IsJumpMontagePlaying(bool* IsPlayingMontage);
	void ItsaMiracle();
	void JuvenileGrowthBonus(double* GrowthBonus);
	void K2_OnMovementModeChanged(EMovementMode PrevMovementMode, EMovementMode NewMovementMode_0, uint8 PrevCustomMode, uint8 NewCustomMode);
	void LocalPossessed();
	void LocalTick(double DeltaSeconds);
	void MaleSenseNest();
	void Multi_SpawnBloodPool();
	void MulticastYelp();
	void NotifyServerNestElemented(class ASpawn_DragonNest_C* DragonNest, Enum_Elements DamageType);
	void NotifyServerRainWetness(bool IsRainWet_0);
	void OnActorInteraction(class AActor* Actor);
	void OnBileExhaustion();
	void OnBleedUpdated();
	void OnBlendOut_2C1013404CCAC5155AA832AD921CDE1E(class FName NotifyName);
	void OnBlendOut_8A8B854E4A7D922BC055A2806C98FDE6(class FName NotifyName);
	void OnBlendOut_D701171F4E44DA8722DCA78B527B4DE2(class FName NotifyName);
	void OnBlendOut_DD680BA34EF87A0CC91286BDFAA84160(class FName NotifyName);
	void OnBurnUpdated();
	void OnCharacterDeath_All_();
	void OnCharacterDeath_Local_();
	void OnCharacterDeath_Remote_();
	void OnCharacterDeath_Server_();
	void OnCompleted_2C1013404CCAC5155AA832AD921CDE1E(class FName NotifyName);
	void OnCompleted_8A8B854E4A7D922BC055A2806C98FDE6(class FName NotifyName);
	void OnCompleted_D701171F4E44DA8722DCA78B527B4DE2(class FName NotifyName);
	void OnCompleted_DD680BA34EF87A0CC91286BDFAA84160(class FName NotifyName);
	void OnDecayUpdated();
	void OnEnvenomation(uint8 VenomTorpor);
	void OnFlightHit(const struct FVector& NormalImpulse);
	void OnGrowthChanged();
	void OnGrowthStageChangedServer();
	void OnHungerUpdated();
	void OnInterrupted_2C1013404CCAC5155AA832AD921CDE1E(class FName NotifyName);
	void OnInterrupted_8A8B854E4A7D922BC055A2806C98FDE6(class FName NotifyName);
	void OnInterrupted_D701171F4E44DA8722DCA78B527B4DE2(class FName NotifyName);
	void OnInterrupted_DD680BA34EF87A0CC91286BDFAA84160(class FName NotifyName);
	void OnJump();
	void OnJumped();
	void OnLanded(const struct FHitResult& Hit);
	void OnMotionStateChanged();
	void OnMotionStateChangedServer();
	void OnMulticastedEmote(Enum_EmotesDragon Emote);
	void OnNotifyBegin_2C1013404CCAC5155AA832AD921CDE1E(class FName NotifyName);
	void OnNotifyBegin_8A8B854E4A7D922BC055A2806C98FDE6(class FName NotifyName);
	void OnNotifyBegin_D701171F4E44DA8722DCA78B527B4DE2(class FName NotifyName);
	void OnNotifyBegin_DD680BA34EF87A0CC91286BDFAA84160(class FName NotifyName);
	void OnNotifyEnd_2C1013404CCAC5155AA832AD921CDE1E(class FName NotifyName);
	void OnNotifyEnd_8A8B854E4A7D922BC055A2806C98FDE6(class FName NotifyName);
	void OnNotifyEnd_D701171F4E44DA8722DCA78B527B4DE2(class FName NotifyName);
	void OnNotifyEnd_DD680BA34EF87A0CC91286BDFAA84160(class FName NotifyName);
	void OnPoisonedEvent();
	void OnReceiveDamage(bool IsHealDmg, bool ShouldYelp, bool IsCriticalHit);
	void OnRep_BaseEmissiveHueValue();
	void OnRep_BleedStacks();
	void OnRep_BurnStacks();
	void OnRep_CosmeticFX();
	void OnRep_DecayStacks();
	void OnRep_HasNest();
	void OnRep_IsBeingCarried();
	void OnRep_ShimmerValue();
	void OnRep_SkinOverride();
	void OnRep_StaticEmissiveHueValue();
	void OnRep_StaticSkinEmissiveValue();
	void OnRep_StunLevels();
	void OnRep_WaterBuoyancy();
	void OnStaminaExhausted(int32 MaxExhaustion);
	void OnStunUpdated();
	void OnSwimStart();
	void OnThirstUpdated();
	void PAI_SetBuoyancy(double Buoyancy);
	void PickupHatchling();
	void PlayStruggleMontageAll();
	void PlayStunnedMontage(class FName StartingSection);
	void poisoned();
	void PrintFlightData();
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void RegenArmor();
	void RegenArmorLoop();
	void RegenHealth();
	void RegenHealthLoop();
	void RegurgitateAll();
	void RegurgitateServer();
	void RemoteTick(double DeltaSeconds);
	void RemoveInvalidEmoteWheelEmotes();
	void RequestMyDragonInfo();
	void ResetCureBleedTimer();
	void ResetCureDecayingTimer();
	void ResetCurePoisonCounter();
	void ResetSplash();
	void RunCarriedLoop();
	void Server_NotifyCourtship(class AChar_Parent_Dragonkind_C* DragonkindMate);
	void Server_Scent(bool Stop);
	void Server_SpawnNest();
	void ServerBeginPlay();
	void ServerCheckSpawnBloodPuddle();
	void ServerCheckSwimming();
	void ServerEndPlay();
	void ServerFlagEggForBrood(class ASpawn_DragonNest_C* Nest, uint8 EggIndex);
	void ServerKeepAwakeCarriedActor();
	void ServerLowerBuoy();
	void ServerMulticastEmote(Enum_EmotesDragon Emote);
	void ServerOnCrashHit();
	void ServerOnPossessed(class AController* Controller_0);
	void ServerOnStruggle();
	void ServerPlayEmote(Enum_EmotesDragon Emote);
	void ServerRaiseBuoy();
	void ServerSpawnSoundwave(const struct FVector& SpawnLocation, const struct FRotator& SpawnRotation, Enum_CrystalColor Attunement);
	void Set_FoodValue();
	void SetDamageStatusEffects(bool ShouldBleed, bool ShouldDecay, bool ShouldBurn, bool ShouldStun);
	void SetEmissiveBaseHueValue(uint8 Value);
	void SetEmissiveStaticHueValue(uint8 Value);
	void SetFlightVisualAudio_FX();
	void SetFullStamina();
	void SetHatchlingKillerEyes();
	void SetShimmerValue(uint8 ShimmerValue_0);
	void SetStaticSkinEmissiveValue(uint8 BrightnessValue);
	void SetValidEmotes();
	void SmellScent();
	void SpecialUsesStatusBar(bool* Return);
	void SphereCheckForLandscape(double SphereRadius, bool* Hit);
	void StopFlight();
	void StopRepMovement();
	void StoreNestID(const class ASpawn_DragonNest_C*& NestActor);
	void StoreStatRecessivesOnLocal(const struct FStruct_StatRecessives& ServerStatModsCopy);
	void StunTempImmunityDecay(double ImmuneDuration);
	void ToggleArmorRegenTimer();
	void ToggleHealthRegenTimer();
	void TryPlayEmote(class FName FunctionName);
	void UserConstructionScript();

	void CheckCanFlyWithWeight(bool* IsLightEnoughToFly) const;
	void GetBoostWithCarried(double* BoostReduction) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Parent_Dragonkind_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Parent_Dragonkind_C")
	}
	static class AChar_Parent_Dragonkind_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Parent_Dragonkind_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_AChar_Parent_Dragonkind_C;

}

