#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Egg_Biolumin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Char_Parent_Egg_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Egg_Biolumin.Char_Egg_Biolumin_C
// 0x0020 (0x1130 - 0x1110)
class AChar_Egg_Biolumin_C final : public AChar_Parent_Egg_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Char_Egg_Biolumin_C;                // 0x1108(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   EmbryoMesh;                                        // 0x1110(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         TimelineOpacity_Time_90FEE1124D8B3B225BF8CA807D16B680; // 0x1118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            TimelineOpacity__Direction_90FEE1124D8B3B225BF8CA807D16B680; // 0x111C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_111D[0x3];                                     // 0x111D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     TimelineOpacity;                                   // 0x1120(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AnimateHatch();
	void ExecuteUbergraph_Char_Egg_Biolumin(int32 EntryPoint);
	void TimelineOpacity__FinishedFunc();
	void TimelineOpacity__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Egg_Biolumin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Egg_Biolumin_C")
	}
	static class AChar_Egg_Biolumin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Egg_Biolumin_C>();
	}
};
DUMPER7_ASSERTS_AChar_Egg_Biolumin_C;

}

