#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Dragon_BroodWatcher

#include "Basic.hpp"

#include "Struct_StatModifiers_structs.hpp"
#include "Struct_BroodWatcherEggTracker_structs.hpp"
#include "Char_Parent_Dragon_classes.hpp"
#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"
#include "Struct_PlayerEggInfo_structs.hpp"
#include "Enum_YawDirection_structs.hpp"
#include "Enum_GeneticGrades_structs.hpp"
#include "Enum_StatMutations_structs.hpp"
#include "Enum_AppliedDamage_structs.hpp"
#include "Enum_AnimMotionStates_structs.hpp"
#include "Enum_GrowthStage_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "Enum_EmotesDragon_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Dragon_BroodWatcher.Char_Dragon_BroodWatcher_C
// 0x00E0 (0x11D0 - 0x10F0)
class AChar_Dragon_BroodWatcher_C final : public AChar_Parent_Dragon_C
{
public:
	uint8                                         Pad_10E3[0x5];                                     // 0x10E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Char_Dragon_BroodWatcher_C;         // 0x10E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          WeaponSwipe;                                       // 0x10F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          WeaponBite;                                        // 0x10F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsFlight_C*                       PhysicsFlight;                                     // 0x1100(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Fade_1E8EA34442592876D71BD29474E4A6D2;  // 0x1108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_1E8EA34442592876D71BD29474E4A6D2; // 0x110C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_110D[0x3];                                     // 0x110D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x1110(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        NV_FadeFloat;                                      // 0x1118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         NumCarriedEggs;                                    // 0x1120(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1121[0x7];                                     // 0x1121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   AttackKey;                                         // 0x1128(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class AActor*>                         BiteActors;                                        // 0x1140(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TSet<class AActor*>                           SwipedActors;                                      // 0x1150(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          IsSwiping;                                         // 0x11A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_YawDirection                             SwipeDirection;                                    // 0x11A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsTailAttackOnCooldown;                            // 0x11A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11A3[0x5];                                     // 0x11A3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStruct_PlayerEggInfo>          BroodingPouchEggs;                                 // 0x11A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FStruct_BroodWatcherEggTracker         BroodPouchEggTracker;                              // 0x11B8(0x0002)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         EggIncubationPercentL1;                            // 0x11BA(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         EggIncubationPercentR2;                            // 0x11BB(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         TotalCritAttempts1;                                // 0x11BC(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CritSuccesses1;                                    // 0x11BD(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         TotalCritAttempts2;                                // 0x11BE(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CritSuccesses2;                                    // 0x11BF(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(uint8 Event, const struct FStruct_StatModifiers& Stats)> OnBroodCraftAttempt; // 0x11C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void AllGlideJump();
	void ApplySkin();
	void AssignNewEggGene(const struct FStruct_PlayerEggInfo& OldEgg, uint8 GeneIndex, int32 CritResult, struct FStruct_PlayerEggInfo* NewEgg);
	void BndEvt__Char_Dragon_FlameStalker_WeaponBite_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__Char_Dragon_FlameStalker_WeaponSwipe_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void CalculateAllBroodingCrits(uint8 CritAttempts, double* CritChance, double* SuperCritChance, double* FailChance, double* CritFailChance);
	void CalculateBroodCritChance(uint8 CritAttempts, uint8* CritChance);
	void CheckValidEmotePerSpecies(Enum_EmotesDragon Emote, bool HasEmotePack, bool* IsValidEmote);
	void ClientDispatchCraftTxtEvent(uint8 EventID, const struct FStruct_StatModifiers& EggStats);
	void ClientUpdateBroodEggs(const TArray<struct FStruct_PlayerEggInfo>& Eggs);
	Enum_GeneticGrades ConvertGenes(int32 CritResult, int32 GeneByte);
	void ExecuteUbergraph_Char_Dragon_BroodWatcher(int32 EntryPoint);
	void GetBroodPouch(bool* HasEggs, TArray<struct FStruct_PlayerEggInfo>* BroodingPouchEggs_0);
	void GetDamageModifiers(double InDamage, Enum_AppliedDamage DamageSource, double* OutDamage);
	void GetElementBileCost(uint8* BileCost);
	void GetNewGeneValue(uint8 CritAttempts, int32* CritValue, uint8* EventID);
	void GetSpecialSkinIndexes(uint8* Birthright, uint8* InfusedCrimson, uint8* Albino);
	void GetStamDrainMultipliers(int32* DrainMultiplier);
	void GetStamRegenMultipliers(int32* RegenMultiplier);
	void HasAnyEggs(bool* HasEggs);
	void HasEgg1(bool* HasEgg1_0);
	void HasEgg2(bool* HasEgg2_0);
	void HornAll();
	void HornServer();
	void IncreaseHunger();
	void InpActEvt_Attack2_K2Node_InputActionEvent_1(const struct FKey& Key);
	void InpActEvt_Attack_K2Node_InputActionEvent_0(const struct FKey& Key);
	void LocalTick(double DeltaSeconds);
	void MulticastSpikeThrow(const struct FVector& TargetLoc, const struct FVector& LocalCameraLoc);
	void NotifyServerSpikeThrow(const struct FVector& TargetLoc, const struct FVector& LocalCameraLoc);
	void OnBlendOut_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName);
	void OnBlendOut_3872EC4A43B4343191551883D031C95F(class FName NotifyName);
	void OnBlendOut_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName);
	void OnBlendOut_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName);
	void OnBlendOut_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName);
	void OnBlendOut_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName);
	void OnCompleted_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName);
	void OnCompleted_3872EC4A43B4343191551883D031C95F(class FName NotifyName);
	void OnCompleted_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName);
	void OnCompleted_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName);
	void OnCompleted_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName);
	void OnCompleted_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName);
	void OnInterrupted_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName);
	void OnInterrupted_3872EC4A43B4343191551883D031C95F(class FName NotifyName);
	void OnInterrupted_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName);
	void OnInterrupted_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName);
	void OnInterrupted_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName);
	void OnInterrupted_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName);
	void OnJump();
	void OnJumped();
	void OnLanded(const struct FHitResult& Hit);
	void OnMulticastedEmote(Enum_EmotesDragon Emote);
	void OnNotifyBegin_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName);
	void OnNotifyBegin_3872EC4A43B4343191551883D031C95F(class FName NotifyName);
	void OnNotifyBegin_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName);
	void OnNotifyBegin_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName);
	void OnNotifyBegin_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName);
	void OnNotifyBegin_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName);
	void OnNotifyEnd_0D0C28034CC69F3F8D003E9DB005B091(class FName NotifyName);
	void OnNotifyEnd_3872EC4A43B4343191551883D031C95F(class FName NotifyName);
	void OnNotifyEnd_45BA59314E10CB3E47E6A19C6BBA884E(class FName NotifyName);
	void OnNotifyEnd_977E1ACF4EB9DB9761904AA70C9B60CB(class FName NotifyName);
	void OnNotifyEnd_D102FEBE4FD5CAD9A5E97E884CE486C5(class FName NotifyName);
	void OnNotifyEnd_DB2FD6C5454834C97C8757830A80F316(class FName NotifyName);
	void ReceiveAsyncPhysicsTick(float DeltaSeconds, float SimSeconds);
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void ServerAttemptEnhanceStat(uint8 EggIndex, uint8 GeneIndex);
	void ServerGlideJump();
	void ServerRequestPouchInterface();
	void SpecialUsesStatusBar(bool* Return);
	void SwipeAll(Enum_YawDirection Direction);
	void SwipeServer(Enum_YawDirection Direction);
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Dragon_BroodWatcher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Dragon_BroodWatcher_C")
	}
	static class AChar_Dragon_BroodWatcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Dragon_BroodWatcher_C>();
	}
};
DUMPER7_ASSERTS_AChar_Dragon_BroodWatcher_C;

}

