#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Char_Wyvern_SingeCrest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Char_Parent_Wyvern_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Char_Wyvern_SingeCrest.Char_Wyvern_SingeCrest_C
// 0x0030 (0x1120 - 0x10F0)
class AChar_Wyvern_SingeCrest_C final : public AChar_Parent_Wyvern_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Char_Wyvern_SingeCrest_C;           // 0x10F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          UseLookAt;                                         // 0x10F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10F9[0x7];                                     // 0x10F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                LookAtPoint;                                       // 0x1100(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MembraneMorphMultiplier;                           // 0x1118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Char_Wyvern_SingeCrest(int32 EntryPoint);
	void GetSpecialSkinIndexes(uint8* Birthright, uint8* InfusedCrimson, uint8* Albino);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Char_Wyvern_SingeCrest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Char_Wyvern_SingeCrest_C")
	}
	static class AChar_Wyvern_SingeCrest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChar_Wyvern_SingeCrest_C>();
	}
};
DUMPER7_ASSERTS_AChar_Wyvern_SingeCrest_C;

}

