#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dragons

#include "Basic.hpp"


namespace SDK
{

// Enum Dragons.ESecurityViolationType
// NumValues: 0x0006
enum class ESecurityViolationType : uint8
{
	None                                     = 0,
	ForbiddenModule                          = 1,
	ProxyInjection                           = 2,
	WindowSubclassing                        = 3,
	OverlayViolation                         = 4,
	ESecurityViolationType_MAX               = 5,
};

}

