#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EIKWeb

#include "Basic.hpp"

#include "EIKWeb_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class EIKWeb.EIK_BaseWebApi
// 0x0020 (0x0050 - 0x0030)
class UEIK_BaseWebApi : public UBlueprintAsyncActionBase
{
public:
	TMulticastInlineDelegate<void(bool bSuccess, const struct FEIK_BaseWebApiResponse& Response)> OnResponse; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_40[0x10];                                      // 0x0040(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_BaseWebApi")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_BaseWebApi")
	}
	static class UEIK_BaseWebApi* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_BaseWebApi>();
	}
};
DUMPER7_ASSERTS_UEIK_BaseWebApi;

// Class EIKWeb.EIK_API_ApprovePendingSanctions
// 0x0060 (0x00B0 - 0x0050)
class UEIK_API_ApprovePendingSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x60];                                      // 0x0050(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_ApprovePendingSanctions* ApprovePendingSanctions(const class FString& Authorization, const class FString& DeploymentId, const class FString& EOS_OrganizationId, const class FString& EOS_ClientId, const class FString& EOS_DeploymentId, const TArray<class FString>& ReferenceIds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_ApprovePendingSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_ApprovePendingSanctions")
	}
	static class UEIK_API_ApprovePendingSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_ApprovePendingSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_ApprovePendingSanctions;

// Class EIKWeb.EIK_API_BulkQueryActiveSanction
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_BulkQueryActiveSanction final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_BulkQueryActiveSanction* BulkQueryActiveSanction(const class FString& Authorization, const class FString& DeploymentId, const TArray<class FString>& ProductUserId, const TArray<class FString>& Action);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_BulkQueryActiveSanction")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_BulkQueryActiveSanction")
	}
	static class UEIK_API_BulkQueryActiveSanction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_BulkQueryActiveSanction>();
	}
};
DUMPER7_ASSERTS_UEIK_API_BulkQueryActiveSanction;

// Class EIKWeb.EIK_API_CreateRoomTokens
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_CreateRoomTokens final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_CreateRoomTokens* CreateVoiceRoomToken(const class FString& Authorization, const class FString& DeploymentId, const class FString& RoomId, const TArray<struct FEWebApi_EosRoomParticipant>& Participants);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_CreateRoomTokens")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_CreateRoomTokens")
	}
	static class UEIK_API_CreateRoomTokens* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_CreateRoomTokens>();
	}
};
DUMPER7_ASSERTS_UEIK_API_CreateRoomTokens;

// Class EIKWeb.EIK_API_CreateSanctionAppealForLocalUser
// 0x0050 (0x00A0 - 0x0050)
class UEIK_API_CreateSanctionAppealForLocalUser final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x50];                                      // 0x0050(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_CreateSanctionAppealForLocalUser* CreateSanctionAppealForLocalUser(const class FString& Authorization, const class FString& DeploymentId, const class FString& ProductUserId, const class FString& ReferenceId, const class FString& Reason);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_CreateSanctionAppealForLocalUser")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_CreateSanctionAppealForLocalUser")
	}
	static class UEIK_API_CreateSanctionAppealForLocalUser* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_CreateSanctionAppealForLocalUser>();
	}
};
DUMPER7_ASSERTS_UEIK_API_CreateSanctionAppealForLocalUser;

// Class EIKWeb.EIK_API_CreateSanctionAppeals
// 0x0038 (0x0088 - 0x0050)
class UEIK_API_CreateSanctionAppeals final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x38];                                      // 0x0050(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_CreateSanctionAppeals* CreateSanctionAppeals(const class FString& Authorization, const class FString& DeploymentId, const class FString& ReferenceId, int32 Reason);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_CreateSanctionAppeals")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_CreateSanctionAppeals")
	}
	static class UEIK_API_CreateSanctionAppeals* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_CreateSanctionAppeals>();
	}
};
DUMPER7_ASSERTS_UEIK_API_CreateSanctionAppeals;

// Class EIKWeb.EIK_API_CreateSanctions
// 0x0030 (0x0080 - 0x0050)
class UEIK_API_CreateSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_CreateSanctions* CreateSanctions(const class FString& Authorization, const class FString& DeploymentId, const TArray<struct FEIK_SanctionPostPayload>& Sanctions);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_CreateSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_CreateSanctions")
	}
	static class UEIK_API_CreateSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_CreateSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_CreateSanctions;

// Class EIKWeb.EIK_API_DirectEntitlementEnumeration
// 0x0048 (0x0098 - 0x0050)
class UEIK_API_DirectEntitlementEnumeration final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x48];                                      // 0x0050(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_DirectEntitlementEnumeration* DirectEntitlementEnumeration(const class FString& Authorization, const class FString& IdentityId, const class FString& SandboxId, const class FString& EntitlementName, bool bIncludeRedeemed);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_DirectEntitlementEnumeration")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_DirectEntitlementEnumeration")
	}
	static class UEIK_API_DirectEntitlementEnumeration* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_DirectEntitlementEnumeration>();
	}
};
DUMPER7_ASSERTS_UEIK_API_DirectEntitlementEnumeration;

// Class EIKWeb.EIK_API_DirectOwnershipVerification
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_DirectOwnershipVerification final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_DirectOwnershipVerification* DirectOwnershipVerification(const class FString& Authorization, const class FString& CurrentAccountId, const TArray<class FString>& NsCatalogItemIds, const class FString& SandboxId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_DirectOwnershipVerification")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_DirectOwnershipVerification")
	}
	static class UEIK_API_DirectOwnershipVerification* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_DirectOwnershipVerification>();
	}
};
DUMPER7_ASSERTS_UEIK_API_DirectOwnershipVerification;

// Class EIKWeb.EIK_API_FindPlayerReports
// 0x0088 (0x00D8 - 0x0050)
class UEIK_API_FindPlayerReports final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x88];                                      // 0x0050(0x0088)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_FindPlayerReports* FindPlayerReports(const class FString& Authorization, const class FString& DeploymentId, const class FString& ReportingPlayerId, const class FString& ReportedPlayerId, int32 ReasonId, const class FString& StartTime, const class FString& EndTime, bool bPagination, int32 Offset, int32 Limit, const class FString& Order);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_FindPlayerReports")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_FindPlayerReports")
	}
	static class UEIK_API_FindPlayerReports* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_FindPlayerReports>();
	}
};
DUMPER7_ASSERTS_UEIK_API_FindPlayerReports;

// Class EIKWeb.EIK_API_GetReportReasonDefinition
// 0x0010 (0x0060 - 0x0050)
class UEIK_API_GetReportReasonDefinition final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_GetReportReasonDefinition* GetReportReasonDefinition(const class FString& Authorization);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_GetReportReasonDefinition")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_GetReportReasonDefinition")
	}
	static class UEIK_API_GetReportReasonDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_GetReportReasonDefinition>();
	}
};
DUMPER7_ASSERTS_UEIK_API_GetReportReasonDefinition;

// Class EIKWeb.EIK_API_ModifyParticipant
// 0x0048 (0x0098 - 0x0050)
class UEIK_API_ModifyParticipant final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x48];                                      // 0x0050(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_ModifyParticipant* ModifyParticipant(const class FString& Authorization, const class FString& DeploymentId, const class FString& RoomId, const class FString& ProductUserId, bool bHardMuted);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_ModifyParticipant")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_ModifyParticipant")
	}
	static class UEIK_API_ModifyParticipant* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_ModifyParticipant>();
	}
};
DUMPER7_ASSERTS_UEIK_API_ModifyParticipant;

// Class EIKWeb.EIK_API_QueryActiveSanctions
// 0x0030 (0x0080 - 0x0050)
class UEIK_API_QueryActiveSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryActiveSanctions* QueryActiveSanctions(const class FString& Authorization, const class FString& ProductUserId, const TArray<class FString>& Action);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryActiveSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryActiveSanctions")
	}
	static class UEIK_API_QueryActiveSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryActiveSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryActiveSanctions;

// Class EIKWeb.EIK_API_QueryAllSanctions
// 0x0028 (0x0078 - 0x0050)
class UEIK_API_QueryAllSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x28];                                      // 0x0050(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryAllSanctions* QueryAllSanctions(const class FString& Authorization, const class FString& DeploymentId, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryAllSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryAllSanctions")
	}
	static class UEIK_API_QueryAllSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryAllSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryAllSanctions;

// Class EIKWeb.EIK_API_QueryAllSanctionsForPlayer
// 0x0038 (0x0088 - 0x0050)
class UEIK_API_QueryAllSanctionsForPlayer final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x38];                                      // 0x0050(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryAllSanctionsForPlayer* QueryAllSanctionsForPlayer(const class FString& Authorization, const class FString& DeploymentId, const class FString& ProductUserId, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryAllSanctionsForPlayer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryAllSanctionsForPlayer")
	}
	static class UEIK_API_QueryAllSanctionsForPlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryAllSanctionsForPlayer>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryAllSanctionsForPlayer;

// Class EIKWeb.EIK_API_QueryAntiCheatServiceStatus
// 0x0020 (0x0070 - 0x0050)
class UEIK_API_QueryAntiCheatServiceStatus final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x20];                                      // 0x0050(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryAntiCheatServiceStatus* QueryAntiCheatServiceStatus(const class FString& Authorization, const class FString& DeploymentId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryAntiCheatServiceStatus")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryAntiCheatServiceStatus")
	}
	static class UEIK_API_QueryAntiCheatServiceStatus* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryAntiCheatServiceStatus>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryAntiCheatServiceStatus;

// Class EIKWeb.EIK_API_QueryClawbacks
// 0x0038 (0x0088 - 0x0050)
class UEIK_API_QueryClawbacks final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x38];                                      // 0x0050(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryClawbacks* QueryClawbacks(const class FString& Authorization, const class FString& Namespace, const class FString& ClawbackDate, int32 Count);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryClawbacks")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryClawbacks")
	}
	static class UEIK_API_QueryClawbacks* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryClawbacks>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryClawbacks;

// Class EIKWeb.EIK_API_QueryExternalAccounts
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_QueryExternalAccounts final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryExternalAccounts* QueryExternalAccounts(const class FString& Authorization, const TArray<class FString>& AccountId, const class FString& IdentityProviderId, const class FString& Environment);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryExternalAccounts")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryExternalAccounts")
	}
	static class UEIK_API_QueryExternalAccounts* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryExternalAccounts>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryExternalAccounts;

// Class EIKWeb.EIK_API_QueryOffers
// 0x0030 (0x0080 - 0x0050)
class UEIK_API_QueryOffers final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryOffers* QueryOffers(const class FString& Authorization, const class FString& IdentityId, const class FString& SandboxId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryOffers")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryOffers")
	}
	static class UEIK_API_QueryOffers* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryOffers>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryOffers;

// Class EIKWeb.EIK_API_QueryProductUsers
// 0x0020 (0x0070 - 0x0050)
class UEIK_API_QueryProductUsers final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x20];                                      // 0x0050(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QueryProductUsers* QueryProductUsers(const class FString& Authorization, const TArray<class FString>& ProductUserIds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QueryProductUsers")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QueryProductUsers")
	}
	static class UEIK_API_QueryProductUsers* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QueryProductUsers>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QueryProductUsers;

// Class EIKWeb.EIK_API_QuerySanctionAppeals
// 0x0058 (0x00A8 - 0x0050)
class UEIK_API_QuerySanctionAppeals final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x58];                                      // 0x0050(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_QuerySanctionAppeals* QuerySanctionAppeals(const class FString& Authorization, const class FString& DeploymentId, const class FString& ReferenceId, const class FString& Status, const class FString& ProductUserId, int32 Limit, int32 Offset);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_QuerySanctionAppeals")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_QuerySanctionAppeals")
	}
	static class UEIK_API_QuerySanctionAppeals* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_QuerySanctionAppeals>();
	}
};
DUMPER7_ASSERTS_UEIK_API_QuerySanctionAppeals;

// Class EIKWeb.EIK_API_RedeemEntitlements
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_RedeemEntitlements final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_RedeemEntitlements* RedeemEntitlements(const class FString& Authorization, const class FString& IdentityId, const TArray<class FString>& EntitlementIds, const class FString& SandboxId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_RedeemEntitlements")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_RedeemEntitlements")
	}
	static class UEIK_API_RedeemEntitlements* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_RedeemEntitlements>();
	}
};
DUMPER7_ASSERTS_UEIK_API_RedeemEntitlements;

// Class EIKWeb.EIK_API_RemoveSanctions
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_RemoveSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_RemoveSanctions* RemoveSanctions(const class FString& Authorization, const class FString& DeploymentId, const TArray<class FString>& ReferenceIds, const class FString& Justification);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_RemoveSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_RemoveSanctions")
	}
	static class UEIK_API_RemoveSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_RemoveSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_RemoveSanctions;

// Class EIKWeb.EIK_API_RemoveVoiceParticipant
// 0x0040 (0x0090 - 0x0050)
class UEIK_API_RemoveVoiceParticipant final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_RemoveVoiceParticipant* RemoveVoiceParticipant(const class FString& Authorization, const class FString& DeploymentId, const class FString& RoomId, const class FString& ProductUserId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_RemoveVoiceParticipant")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_RemoveVoiceParticipant")
	}
	static class UEIK_API_RemoveVoiceParticipant* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_RemoveVoiceParticipant>();
	}
};
DUMPER7_ASSERTS_UEIK_API_RemoveVoiceParticipant;

// Class EIKWeb.EIK_API_RequestAccessToken
// 0x0080 (0x00D0 - 0x0050)
class UEIK_API_RequestAccessToken final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x80];                                      // 0x0050(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_RequestAccessToken* RequestAccessToken(const class FString& Authorization, const class FString& ClientId, const class FString& ClientSecret, const class FString& GrantType, const class FString& Nonce, const class FString& DeploymentId, const class FString& ExternalAuthToken, const class FString& ExternalAuthType);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_RequestAccessToken")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_RequestAccessToken")
	}
	static class UEIK_API_RequestAccessToken* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_RequestAccessToken>();
	}
};
DUMPER7_ASSERTS_UEIK_API_RequestAccessToken;

// Class EIKWeb.EIK_API_SendNewPlayerReport
// 0x0068 (0x00B8 - 0x0050)
class UEIK_API_SendNewPlayerReport final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x68];                                      // 0x0050(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_SendNewPlayerReport* SendNewPlayerReport(const class FString& Authorization, const class FString& ReportingPlayerId, const class FString& ReportedPlayerId, const class FString& Time, int32 ReasonId, const class FString& Message, const class FString& Context);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_SendNewPlayerReport")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_SendNewPlayerReport")
	}
	static class UEIK_API_SendNewPlayerReport* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_SendNewPlayerReport>();
	}
};
DUMPER7_ASSERTS_UEIK_API_SendNewPlayerReport;

// Class EIKWeb.EIK_API_SyncSanctionsToExternalService
// 0x0020 (0x0070 - 0x0050)
class UEIK_API_SyncSanctionsToExternalService final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x20];                                      // 0x0050(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_SyncSanctionsToExternalService* SyncSanctionsToExternalService(const class FString& Authorization, const class FString& LastLogId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_SyncSanctionsToExternalService")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_SyncSanctionsToExternalService")
	}
	static class UEIK_API_SyncSanctionsToExternalService* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_SyncSanctionsToExternalService>();
	}
};
DUMPER7_ASSERTS_UEIK_API_SyncSanctionsToExternalService;

// Class EIKWeb.EIK_API_TokenBasedEntitlementVerification
// 0x0000 (0x0050 - 0x0050)
class UEIK_API_TokenBasedEntitlementVerification final : public UEIK_BaseWebApi
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_TokenBasedEntitlementVerification")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_TokenBasedEntitlementVerification")
	}
	static class UEIK_API_TokenBasedEntitlementVerification* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_TokenBasedEntitlementVerification>();
	}
};
DUMPER7_ASSERTS_UEIK_API_TokenBasedEntitlementVerification;

// Class EIKWeb.EIK_API_TokenBasedOwnershipVerification
// 0x0080 (0x00D0 - 0x0050)
class UEIK_API_TokenBasedOwnershipVerification final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x80];                                      // 0x0050(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_TokenBasedOwnershipVerification* TokenBasedOwnershipVerification(const class FString& AuthorizationToken, const class FString& Platform, const class FString& IdentityId, const TMap<class FString, class FString>& CatalogItemId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_TokenBasedOwnershipVerification")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_TokenBasedOwnershipVerification")
	}
	static class UEIK_API_TokenBasedOwnershipVerification* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_TokenBasedOwnershipVerification>();
	}
};
DUMPER7_ASSERTS_UEIK_API_TokenBasedOwnershipVerification;

// Class EIKWeb.EIK_API_UpdatingSanctions
// 0x0030 (0x0080 - 0x0050)
class UEIK_API_UpdatingSanctions final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_UpdatingSanctions* UpdatingSanctions(const class FString& Authorization, const class FString& DeploymentId, const TArray<struct FEIK_SanctionPatchPayload>& SanctionPatchPayload);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_UpdatingSanctions")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_UpdatingSanctions")
	}
	static class UEIK_API_UpdatingSanctions* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_UpdatingSanctions>();
	}
};
DUMPER7_ASSERTS_UEIK_API_UpdatingSanctions;

// Class EIKWeb.EIK_API_VerifyEntitlementVerificationToken
// 0x0010 (0x0060 - 0x0050)
class UEIK_API_VerifyEntitlementVerificationToken final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_VerifyEntitlementVerificationToken* VerifyEntitlementVerificationToken(const class FString& KeyId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_VerifyEntitlementVerificationToken")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_VerifyEntitlementVerificationToken")
	}
	static class UEIK_API_VerifyEntitlementVerificationToken* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_VerifyEntitlementVerificationToken>();
	}
};
DUMPER7_ASSERTS_UEIK_API_VerifyEntitlementVerificationToken;

// Class EIKWeb.EIK_API_VerifyOwnershipVerificationToken
// 0x0010 (0x0060 - 0x0050)
class UEIK_API_VerifyOwnershipVerificationToken final : public UEIK_BaseWebApi
{
public:
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UEIK_API_VerifyOwnershipVerificationToken* VerifyOwnershipVerificationToken(const class FString& KeyId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EIK_API_VerifyOwnershipVerificationToken")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EIK_API_VerifyOwnershipVerificationToken")
	}
	static class UEIK_API_VerifyOwnershipVerificationToken* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEIK_API_VerifyOwnershipVerificationToken>();
	}
};
DUMPER7_ASSERTS_UEIK_API_VerifyOwnershipVerificationToken;

}

