#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EIKWeb

#include "Basic.hpp"

#include "EIKWeb_structs.hpp"


namespace SDK::Params
{

// Function EIKWeb.EIK_API_ApprovePendingSanctions.ApprovePendingSanctions
// 0x0068 (0x0068 - 0x0000)
struct EIK_API_ApprovePendingSanctions_ApprovePendingSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EOS_OrganizationId;                                // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EOS_ClientId;                                      // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EOS_DeploymentId;                                  // 0x0040(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         ReferenceIds;                                      // 0x0050(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_ApprovePendingSanctions*       ReturnValue;                                       // 0x0060(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_ApprovePendingSanctions_ApprovePendingSanctions;

// Function EIKWeb.EIK_API_BulkQueryActiveSanction.BulkQueryActiveSanction
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_BulkQueryActiveSanction_BulkQueryActiveSanction final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         ProductUserId;                                     // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class FString>                         Action;                                            // 0x0030(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_BulkQueryActiveSanction*       ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_BulkQueryActiveSanction_BulkQueryActiveSanction;

// Function EIKWeb.EIK_API_CreateRoomTokens.CreateVoiceRoomToken
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_CreateRoomTokens_CreateVoiceRoomToken final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoomId;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FEWebApi_EosRoomParticipant>    Participants;                                      // 0x0030(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_CreateRoomTokens*              ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_CreateRoomTokens_CreateVoiceRoomToken;

// Function EIKWeb.EIK_API_CreateSanctionAppealForLocalUser.CreateSanctionAppealForLocalUser
// 0x0058 (0x0058 - 0x0000)
struct EIK_API_CreateSanctionAppealForLocalUser_CreateSanctionAppealForLocalUser final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReferenceId;                                       // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Reason;                                            // 0x0040(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_CreateSanctionAppealForLocalUser* ReturnValue;                                    // 0x0050(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_CreateSanctionAppealForLocalUser_CreateSanctionAppealForLocalUser;

// Function EIKWeb.EIK_API_CreateSanctionAppeals.CreateSanctionAppeals
// 0x0040 (0x0040 - 0x0000)
struct EIK_API_CreateSanctionAppeals_CreateSanctionAppeals final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReferenceId;                                       // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Reason;                                            // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UEIK_API_CreateSanctionAppeals*         ReturnValue;                                       // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_CreateSanctionAppeals_CreateSanctionAppeals;

// Function EIKWeb.EIK_API_CreateSanctions.CreateSanctions
// 0x0038 (0x0038 - 0x0000)
struct EIK_API_CreateSanctions_CreateSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FEIK_SanctionPostPayload>       Sanctions;                                         // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_CreateSanctions*               ReturnValue;                                       // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_CreateSanctions_CreateSanctions;

// Function EIKWeb.EIK_API_DirectEntitlementEnumeration.DirectEntitlementEnumeration
// 0x0050 (0x0050 - 0x0000)
struct EIK_API_DirectEntitlementEnumeration_DirectEntitlementEnumeration final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 IdentityId;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SandboxId;                                         // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EntitlementName;                                   // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeRedeemed;                                  // 0x0040(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UEIK_API_DirectEntitlementEnumeration*  ReturnValue;                                       // 0x0048(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_DirectEntitlementEnumeration_DirectEntitlementEnumeration;

// Function EIKWeb.EIK_API_DirectOwnershipVerification.DirectOwnershipVerification
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_DirectOwnershipVerification_DirectOwnershipVerification final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CurrentAccountId;                                  // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         NsCatalogItemIds;                                  // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 SandboxId;                                         // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_DirectOwnershipVerification*   ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_DirectOwnershipVerification_DirectOwnershipVerification;

// Function EIKWeb.EIK_API_FindPlayerReports.FindPlayerReports
// 0x0090 (0x0090 - 0x0000)
struct EIK_API_FindPlayerReports_FindPlayerReports final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReportingPlayerId;                                 // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReportedPlayerId;                                  // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReasonId;                                          // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 StartTime;                                         // 0x0048(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EndTime;                                           // 0x0058(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPagination;                                       // 0x0068(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Offset;                                            // 0x006C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Limit;                                             // 0x0070(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Order;                                             // 0x0078(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_FindPlayerReports*             ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_FindPlayerReports_FindPlayerReports;

// Function EIKWeb.EIK_API_GetReportReasonDefinition.GetReportReasonDefinition
// 0x0018 (0x0018 - 0x0000)
struct EIK_API_GetReportReasonDefinition_GetReportReasonDefinition final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_GetReportReasonDefinition*     ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_GetReportReasonDefinition_GetReportReasonDefinition;

// Function EIKWeb.EIK_API_ModifyParticipant.ModifyParticipant
// 0x0050 (0x0050 - 0x0000)
struct EIK_API_ModifyParticipant_ModifyParticipant final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoomId;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHardMuted;                                        // 0x0040(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UEIK_API_ModifyParticipant*             ReturnValue;                                       // 0x0048(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_ModifyParticipant_ModifyParticipant;

// Function EIKWeb.EIK_API_QueryActiveSanctions.QueryActiveSanctions
// 0x0038 (0x0038 - 0x0000)
struct EIK_API_QueryActiveSanctions_QueryActiveSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         Action;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_QueryActiveSanctions*          ReturnValue;                                       // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryActiveSanctions_QueryActiveSanctions;

// Function EIKWeb.EIK_API_QueryAllSanctions.QueryAllSanctions
// 0x0030 (0x0030 - 0x0000)
struct EIK_API_QueryAllSanctions_QueryAllSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Limit;                                             // 0x0020(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Offset;                                            // 0x0024(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QueryAllSanctions*             ReturnValue;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryAllSanctions_QueryAllSanctions;

// Function EIKWeb.EIK_API_QueryAllSanctionsForPlayer.QueryAllSanctionsForPlayer
// 0x0040 (0x0040 - 0x0000)
struct EIK_API_QueryAllSanctionsForPlayer_QueryAllSanctionsForPlayer final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Limit;                                             // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Offset;                                            // 0x0034(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QueryAllSanctionsForPlayer*    ReturnValue;                                       // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryAllSanctionsForPlayer_QueryAllSanctionsForPlayer;

// Function EIKWeb.EIK_API_QueryAntiCheatServiceStatus.QueryAntiCheatServiceStatus
// 0x0028 (0x0028 - 0x0000)
struct EIK_API_QueryAntiCheatServiceStatus_QueryAntiCheatServiceStatus final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QueryAntiCheatServiceStatus*   ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryAntiCheatServiceStatus_QueryAntiCheatServiceStatus;

// Function EIKWeb.EIK_API_QueryClawbacks.QueryClawbacks
// 0x0040 (0x0040 - 0x0000)
struct EIK_API_QueryClawbacks_QueryClawbacks final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Namespace;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClawbackDate;                                      // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Count;                                             // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UEIK_API_QueryClawbacks*                ReturnValue;                                       // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryClawbacks_QueryClawbacks;

// Function EIKWeb.EIK_API_QueryExternalAccounts.QueryExternalAccounts
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_QueryExternalAccounts_QueryExternalAccounts final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         AccountId;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 IdentityProviderId;                                // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Environment;                                       // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QueryExternalAccounts*         ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryExternalAccounts_QueryExternalAccounts;

// Function EIKWeb.EIK_API_QueryOffers.QueryOffers
// 0x0038 (0x0038 - 0x0000)
struct EIK_API_QueryOffers_QueryOffers final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 IdentityId;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SandboxId;                                         // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QueryOffers*                   ReturnValue;                                       // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryOffers_QueryOffers;

// Function EIKWeb.EIK_API_QueryProductUsers.QueryProductUsers
// 0x0028 (0x0028 - 0x0000)
struct EIK_API_QueryProductUsers_QueryProductUsers final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         ProductUserIds;                                    // 0x0010(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_QueryProductUsers*             ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QueryProductUsers_QueryProductUsers;

// Function EIKWeb.EIK_API_QuerySanctionAppeals.QuerySanctionAppeals
// 0x0060 (0x0060 - 0x0000)
struct EIK_API_QuerySanctionAppeals_QuerySanctionAppeals final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReferenceId;                                       // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Status;                                            // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0040(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Limit;                                             // 0x0050(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Offset;                                            // 0x0054(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_QuerySanctionAppeals*          ReturnValue;                                       // 0x0058(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_QuerySanctionAppeals_QuerySanctionAppeals;

// Function EIKWeb.EIK_API_RedeemEntitlements.RedeemEntitlements
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_RedeemEntitlements_RedeemEntitlements final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 IdentityId;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         EntitlementIds;                                    // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 SandboxId;                                         // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_RedeemEntitlements*            ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_RedeemEntitlements_RedeemEntitlements;

// Function EIKWeb.EIK_API_RemoveSanctions.RemoveSanctions
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_RemoveSanctions_RemoveSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         ReferenceIds;                                      // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 Justification;                                     // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_RemoveSanctions*               ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_RemoveSanctions_RemoveSanctions;

// Function EIKWeb.EIK_API_RemoveVoiceParticipant.RemoveVoiceParticipant
// 0x0048 (0x0048 - 0x0000)
struct EIK_API_RemoveVoiceParticipant_RemoveVoiceParticipant final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RoomId;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ProductUserId;                                     // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_RemoveVoiceParticipant*        ReturnValue;                                       // 0x0040(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_RemoveVoiceParticipant_RemoveVoiceParticipant;

// Function EIKWeb.EIK_API_RequestAccessToken.RequestAccessToken
// 0x0088 (0x0088 - 0x0000)
struct EIK_API_RequestAccessToken_RequestAccessToken final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClientId;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClientSecret;                                      // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 GrantType;                                         // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Nonce;                                             // 0x0040(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0050(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ExternalAuthToken;                                 // 0x0060(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ExternalAuthType;                                  // 0x0070(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_RequestAccessToken*            ReturnValue;                                       // 0x0080(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_RequestAccessToken_RequestAccessToken;

// Function EIKWeb.EIK_API_SendNewPlayerReport.SendNewPlayerReport
// 0x0070 (0x0070 - 0x0000)
struct EIK_API_SendNewPlayerReport_SendNewPlayerReport final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReportingPlayerId;                                 // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReportedPlayerId;                                  // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Time;                                              // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReasonId;                                          // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Message;                                           // 0x0048(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Context;                                           // 0x0058(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_SendNewPlayerReport*           ReturnValue;                                       // 0x0068(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_SendNewPlayerReport_SendNewPlayerReport;

// Function EIKWeb.EIK_API_SyncSanctionsToExternalService.SyncSanctionsToExternalService
// 0x0028 (0x0028 - 0x0000)
struct EIK_API_SyncSanctionsToExternalService_SyncSanctionsToExternalService final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 LastLogId;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_SyncSanctionsToExternalService* ReturnValue;                                      // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_SyncSanctionsToExternalService_SyncSanctionsToExternalService;

// Function EIKWeb.EIK_API_TokenBasedOwnershipVerification.TokenBasedOwnershipVerification
// 0x0088 (0x0088 - 0x0000)
struct EIK_API_TokenBasedOwnershipVerification_TokenBasedOwnershipVerification final
{
public:
	class FString                                 AuthorizationToken;                                // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Platform;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 IdentityId;                                        // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            CatalogItemId;                                     // 0x0030(0x0050)(Parm, NativeAccessSpecifierPublic)
	class UEIK_API_TokenBasedOwnershipVerification* ReturnValue;                                     // 0x0080(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_TokenBasedOwnershipVerification_TokenBasedOwnershipVerification;

// Function EIKWeb.EIK_API_UpdatingSanctions.UpdatingSanctions
// 0x0038 (0x0038 - 0x0000)
struct EIK_API_UpdatingSanctions_UpdatingSanctions final
{
public:
	class FString                                 Authorization;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DeploymentId;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FEIK_SanctionPatchPayload>      SanctionPatchPayload;                              // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEIK_API_UpdatingSanctions*             ReturnValue;                                       // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_UpdatingSanctions_UpdatingSanctions;

// Function EIKWeb.EIK_API_VerifyEntitlementVerificationToken.VerifyEntitlementVerificationToken
// 0x0018 (0x0018 - 0x0000)
struct EIK_API_VerifyEntitlementVerificationToken_VerifyEntitlementVerificationToken final
{
public:
	class FString                                 KeyId;                                             // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_VerifyEntitlementVerificationToken* ReturnValue;                                  // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_VerifyEntitlementVerificationToken_VerifyEntitlementVerificationToken;

// Function EIKWeb.EIK_API_VerifyOwnershipVerificationToken.VerifyOwnershipVerificationToken
// 0x0018 (0x0018 - 0x0000)
struct EIK_API_VerifyOwnershipVerificationToken_VerifyOwnershipVerificationToken final
{
public:
	class FString                                 KeyId;                                             // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UEIK_API_VerifyOwnershipVerificationToken* ReturnValue;                                    // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_EIK_API_VerifyOwnershipVerificationToken_VerifyOwnershipVerificationToken;

}

