#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Project_Mode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_Project_Mode.UDS_Project_Mode
// NumValues: 0x0003
enum class EUDS_Project_Mode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	UDS_Project_MAX                          = 2,
};

}

