#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Planet_Lightsource

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_Planet_Lightsource.UDS_Planet_Lightsource
// NumValues: 0x0004
enum class EUDS_Planet_Lightsource : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	UDS_Planet_MAX                           = 3,
};

}

