#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_LensFlareType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_LensFlareType.UDS_LensFlareType
// NumValues: 0x0004
enum class EUDS_LensFlareType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	UDS_MAX                                  = 3,
};

}

