#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Particle_Collision_Mode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_Particle_Collision_Mode.UDS_Particle_Collision_Mode
// NumValues: 0x0004
enum class EUDS_Particle_Collision_Mode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	UDS_Particle_Collision_MAX               = 3,
};

}

