#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VirtualHeightfieldMesh

#include "Basic.hpp"


namespace SDK::Params
{

// Function VirtualHeightfieldMesh.VirtualHeightfieldMeshComponent.GatherHideFlags
// 0x0002 (0x0002 - 0x0000)
struct VirtualHeightfieldMeshComponent_GatherHideFlags final
{
public:
	bool                                          InOutHidePrimitivesInEditor;                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InOutHidePrimitivesInGame;                         // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VirtualHeightfieldMeshComponent_GatherHideFlags;

}

