#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Nest_GroupPanel

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.ExecuteUbergraph_W_Nest_GroupPanel
// 0x0008 (0x0008 - 0x0000)
struct W_Nest_GroupPanel_C_ExecuteUbergraph_W_Nest_GroupPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Nest_GroupPanel_C_ExecuteUbergraph_W_Nest_GroupPanel;

// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.Get_BG_Background
// 0x01A0 (0x01A0 - 0x0000)
struct W_Nest_GroupPanel_C_Get_BG_Background final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x00D0)(Parm, OutParm, ReturnParm)
	struct FSlateBrush                            CallFunc_GetSkins_PanelMedium_SlateBrush;          // 0x00D0(0x00D0)()
};
DUMPER7_ASSERTS_W_Nest_GroupPanel_C_Get_BG_Background;

// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_Nest_GroupPanel_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Nest_GroupPanel_C_PreConstruct;

}

