#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Nest_GroupPanel

#include "Basic.hpp"

#include "W_Nest_GroupPanel_classes.hpp"
#include "W_Nest_GroupPanel_parameters.hpp"


namespace SDK
{

// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Nest_GroupPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Nest_GroupPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Nest_GroupPanel_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Nest_GroupPanel_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.ExecuteUbergraph_W_Nest_GroupPanel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Nest_GroupPanel_C::ExecuteUbergraph_W_Nest_GroupPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Nest_GroupPanel_C", "ExecuteUbergraph_W_Nest_GroupPanel");

	Params::W_Nest_GroupPanel_C_ExecuteUbergraph_W_Nest_GroupPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.Get_BG_Background
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UW_Nest_GroupPanel_C::Get_BG_Background()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Nest_GroupPanel_C", "Get_BG_Background");

	Params::W_Nest_GroupPanel_C_Get_BG_Background Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Nest_GroupPanel.W_Nest_GroupPanel_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Nest_GroupPanel_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Nest_GroupPanel_C", "PreConstruct");

	Params::W_Nest_GroupPanel_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

