#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wi_Menu_Settings_Display

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Wi_Parent_Menu_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Wi_Menu_Settings_Display.Wi_Menu_Settings_Display_C
// 0x0038 (0x02C8 - 0x0290)
class UWi_Menu_Settings_Display_C final : public UWi_Parent_Menu_C
{
public:
	class UWi_Menu_DisplayList_CVar_C*            Wi_Menu_DisplayList_CVar;                          // 0x0290(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_DisplayList_CVar_C*            Wi_Menu_DisplayList_CVar_1;                        // 0x0298(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_DisplayList_CVar_C*            Wi_Menu_DisplayList_CVar_3;                        // 0x02A0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_DisplayList_CVar_C*            Wi_Menu_DisplayList_CVar_4;                        // 0x02A8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_DisplayList_CVar_C*            Wi_Menu_DisplayList_CVar_125;                      // 0x02B0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_Slider_CVar_C*                 Wi_Menu_Slider_CVar_1;                             // 0x02B8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWi_Menu_Slider_CVarInput_C*            Wi_Menu_Slider_CVarInput_1;                        // 0x02C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	bool GetbIsEnabled();
	bool GetbIsEnabled_0();
	bool GetbIsEnabled_1();
	ESlateVisibility GetVisibility_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Wi_Menu_Settings_Display_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Wi_Menu_Settings_Display_C")
	}
	static class UWi_Menu_Settings_Display_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWi_Menu_Settings_Display_C>();
	}
};
DUMPER7_ASSERTS_UWi_Menu_Settings_Display_C;

}

