#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wi_Pouch_EggEnhancementSheet

#include "Basic.hpp"

#include "Wi_Pouch_EggEnhancementSheet_classes.hpp"
#include "Wi_Pouch_EggEnhancementSheet_parameters.hpp"


namespace SDK
{

// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_AcidResistBtn_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_AcidResistBtn_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_AcidResistBtn_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_BileProdBtn_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_BileProdBtn_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_BileProdBtn_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_BiteForceBtn_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_BiteForceBtn_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_BiteForceBtn_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_EnduranceBtn_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_EnduranceBtn_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_EnduranceBtn_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_FireResistBtn_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_FireResistBtn_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_FireResistBtn_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_FrostResistBtn_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_FrostResistBtn_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_FrostResistBtn_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_ImpactResistBtn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_ImpactResistBtn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_ImpactResistBtn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_LifeExpectBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_LifeExpectBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_LifeExpectBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_LightningResistBtn_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_LightningResistBtn_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_LightningResistBtn_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_NutrientAbsorbBtn_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_NutrientAbsorbBtn_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_NutrientAbsorbBtn_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_PierceResistBtn_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_PierceResistBtn_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_PierceResistBtn_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_PlasmaResistBtn_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_PlasmaResistBtn_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_PlasmaResistBtn_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_PowerBtn_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_PowerBtn_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_PowerBtn_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_ScaleThickBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_ScaleThickBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_ScaleThickBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_StrengthBtn_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_StrengthBtn_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_StrengthBtn_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_ToxinTolerBtn_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_ToxinTolerBtn_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_ToxinTolerBtn_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_VenomResistBtn_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_VenomResistBtn_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_VenomResistBtn_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.BndEvt__Wi_Pouch_EggEnhancementSheet_WaterRetentBtn_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::BndEvt__Wi_Pouch_EggEnhancementSheet_WaterRetentBtn_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "BndEvt__Wi_Pouch_EggEnhancementSheet_WaterRetentBtn_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWi_Pouch_EggEnhancementSheet_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWi_Pouch_EggEnhancementSheet_C::ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet");

	Params::Wi_Pouch_EggEnhancementSheet_C_ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Get_BG_Background
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWi_Pouch_EggEnhancementSheet_C::Get_BG_Background()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "Get_BG_Background");

	Params::Wi_Pouch_EggEnhancementSheet_C_Get_BG_Background Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWi_Pouch_EggEnhancementSheet_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Wi_Pouch_EggEnhancementSheet_C", "Tick");

	Params::Wi_Pouch_EggEnhancementSheet_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

