#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wi_Pouch_EggEnhancementSheet

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet
// 0x0040 (0x0040 - 0x0000)
struct Wi_Pouch_EggEnhancementSheet_C_ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Wi_Pouch_EggEnhancementSheet_C_ExecuteUbergraph_Wi_Pouch_EggEnhancementSheet;

// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Get_BG_Background
// 0x01A0 (0x01A0 - 0x0000)
struct Wi_Pouch_EggEnhancementSheet_C_Get_BG_Background final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x00D0)(Parm, OutParm, ReturnParm)
	struct FSlateBrush                            CallFunc_GetSkins_PanelMedium_SlateBrush;          // 0x00D0(0x00D0)()
};
DUMPER7_ASSERTS_Wi_Pouch_EggEnhancementSheet_C_Get_BG_Background;

// Function Wi_Pouch_EggEnhancementSheet.Wi_Pouch_EggEnhancementSheet_C.Tick
// 0x003C (0x003C - 0x0000)
struct Wi_Pouch_EggEnhancementSheet_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Wi_Pouch_EggEnhancementSheet_C_Tick;

}

